// Code generated by command: go run avo.go -out ../asm.s -stubs ../asm_stub.go -pkg checksum. DO NOT EDIT.

#include "textflag.h"

// func Add(x *[16]uint32, y *[16]uint32, z *[16]uint32)
// Requires: AVX512F
TEXT ·Add(SB), NOSPLIT, $0-24
	MOVQ      x+0(FP), AX
	VMOVDQU64 (AX), Z0
	MOVQ      y+8(FP), AX
	VMOVDQU64 (AX), Z1
	VPADDD    Z0, Z1, Z0
	MOVQ      z+16(FP), AX
	VMOVDQU64 Z0, (AX)
	RET
