// Code generated by command: go run avo.go -out ../asm.s -stubs ../asm_stub.go -pkg checksum. DO NOT EDIT.

package checksum

// Add adds x and y vectors. Result is stored in vector z.
func Add(x *[16]uint32, y *[16]uint32, z *[16]uint32)
