// Code generated by command: go run avo.go -out ../asm.s -stubs ../asm_stub.go -pkg compare. DO NOT EDIT.

package compare

// Compare compares uint64 array against value.
func Compare(v uint64, x *uint64, z *uint64, count uint64) (uint64, uint64)
