// Code generated by command: go run avo.go -out ../asm.s -stubs ../asm_stub.go -pkg hash. DO NOT EDIT.

#include "textflag.h"

// func Blake34096(blocks **byte, hashes **byte, mask uint16)
// Requires: AVX512BW, AVX512F, AVX512VL
TEXT ·Blake34096(SB), NOSPLIT, $0-18
	MOVQ         blocks+0(FP), AX
	MOVW         mask+16(FP), CX
	XORQ         DX, DX
	MOVD         $0x6a09e667, BX
	VPBROADCASTD BX, Z0
	MOVD         $0xbb67ae85, BX
	VPBROADCASTD BX, Z1
	MOVD         $0x3c6ef372, BX
	VPBROADCASTD BX, Z2
	MOVD         $0xa54ff53a, BX
	VPBROADCASTD BX, Z3
	MOVD         $0x510e527f, BX
	VPBROADCASTD BX, Z4
	MOVD         $0x9b05688c, BX
	VPBROADCASTD BX, Z5
	MOVD         $0x1f83d9ab, BX
	VPBROADCASTD BX, Z6
	MOVD         $0x5be0cd19, BX
	VPBROADCASTD BX, Z7
	MOVD         $0x6a09e667, BX
	MOVD         $0xbb67ae85, SI
	MOVD         $0x3c6ef372, DI
	MOVD         $0xa54ff53a, R8
	MOVD         $0x00000000, R9
	MOVD         $0x00000000, R10
	MOVD         $0x00000040, R11
	MOVD         $0x00000000, R12

loopStart:
	VPBROADCASTW CX, Z8
	TESTW        $0x0001, CX
	JZ           loadEnd0
	MOVQ         (AX), R13
	VMOVDQA64    (R13), Z8

loadEnd0:
	VPBROADCASTW CX, Z9
	TESTW        $0x0002, CX
	JZ           loadEnd1
	MOVQ         8(AX), R13
	VMOVDQA64    (R13), Z9

loadEnd1:
	VPBROADCASTW CX, Z10
	TESTW        $0x0004, CX
	JZ           loadEnd2
	MOVQ         16(AX), R13
	VMOVDQA64    (R13), Z10

loadEnd2:
	VPBROADCASTW CX, Z11
	TESTW        $0x0008, CX
	JZ           loadEnd3
	MOVQ         24(AX), R13
	VMOVDQA64    (R13), Z11

loadEnd3:
	VPBROADCASTW CX, Z12
	TESTW        $0x0010, CX
	JZ           loadEnd4
	MOVQ         32(AX), R13
	VMOVDQA64    (R13), Z12

loadEnd4:
	VPBROADCASTW CX, Z13
	TESTW        $0x0020, CX
	JZ           loadEnd5
	MOVQ         40(AX), R13
	VMOVDQA64    (R13), Z13

loadEnd5:
	VPBROADCASTW CX, Z14
	TESTW        $0x0040, CX
	JZ           loadEnd6
	MOVQ         48(AX), R13
	VMOVDQA64    (R13), Z14

loadEnd6:
	VPBROADCASTW CX, Z15
	TESTW        $0x0080, CX
	JZ           loadEnd7
	MOVQ         56(AX), R13
	VMOVDQA64    (R13), Z15

loadEnd7:
	VPBROADCASTW CX, Z16
	TESTW        $0x0100, CX
	JZ           loadEnd8
	MOVQ         64(AX), R13
	VMOVDQA64    (R13), Z16

loadEnd8:
	VPBROADCASTW CX, Z17
	TESTW        $0x0200, CX
	JZ           loadEnd9
	MOVQ         72(AX), R13
	VMOVDQA64    (R13), Z17

loadEnd9:
	VPBROADCASTW CX, Z18
	TESTW        $0x0400, CX
	JZ           loadEnd10
	MOVQ         80(AX), R13
	VMOVDQA64    (R13), Z18

loadEnd10:
	VPBROADCASTW CX, Z19
	TESTW        $0x0800, CX
	JZ           loadEnd11
	MOVQ         88(AX), R13
	VMOVDQA64    (R13), Z19

loadEnd11:
	VPBROADCASTW CX, Z20
	TESTW        $0x1000, CX
	JZ           loadEnd12
	MOVQ         96(AX), R13
	VMOVDQA64    (R13), Z20

loadEnd12:
	VPBROADCASTW CX, Z21
	TESTW        $0x2000, CX
	JZ           loadEnd13
	MOVQ         104(AX), R13
	VMOVDQA64    (R13), Z21

loadEnd13:
	VPBROADCASTW CX, Z22
	TESTW        $0x4000, CX
	JZ           loadEnd14
	MOVQ         112(AX), R13
	VMOVDQA64    (R13), Z22

loadEnd14:
	VPBROADCASTW CX, Z23
	TESTW        $0x8000, CX
	JZ           loadEnd15
	MOVQ         120(AX), R13
	VMOVDQA64    (R13), Z23

loadEnd15:
	ADDQ         $0x40, DX
	VSHUFPS      $0x44, Z9, Z8, Z24
	VSHUFPS      $0xee, Z9, Z8, Z8
	VSHUFPS      $0x44, Z11, Z10, Z9
	VSHUFPS      $0xee, Z11, Z10, Z10
	VSHUFPS      $0x44, Z13, Z12, Z11
	VSHUFPS      $0xee, Z13, Z12, Z12
	VSHUFPS      $0x44, Z15, Z14, Z13
	VSHUFPS      $0xee, Z15, Z14, Z14
	VSHUFPS      $0x44, Z17, Z16, Z15
	VSHUFPS      $0xee, Z17, Z16, Z16
	VSHUFPS      $0x44, Z19, Z18, Z17
	VSHUFPS      $0xee, Z19, Z18, Z18
	VSHUFPS      $0x44, Z21, Z20, Z19
	VSHUFPS      $0xee, Z21, Z20, Z20
	VSHUFPS      $0x44, Z23, Z22, Z21
	VSHUFPS      $0xee, Z23, Z22, Z22
	VSHUFPS      $0x88, Z9, Z24, Z23
	VSHUFPS      $0xdd, Z9, Z24, Z24
	VSHUFPS      $0x88, Z10, Z8, Z9
	VSHUFPS      $0xdd, Z10, Z8, Z8
	VSHUFPS      $0x88, Z13, Z11, Z10
	VSHUFPS      $0xdd, Z13, Z11, Z11
	VSHUFPS      $0x88, Z14, Z12, Z13
	VSHUFPS      $0xdd, Z14, Z12, Z12
	VSHUFPS      $0x88, Z17, Z15, Z14
	VSHUFPS      $0xdd, Z17, Z15, Z15
	VSHUFPS      $0x88, Z18, Z16, Z17
	VSHUFPS      $0xdd, Z18, Z16, Z16
	VSHUFPS      $0x88, Z21, Z19, Z18
	VSHUFPS      $0xdd, Z21, Z19, Z19
	VSHUFPS      $0x88, Z22, Z20, Z21
	VSHUFPS      $0xdd, Z22, Z20, Z20
	VSHUFI32X4   $0x44, Z10, Z23, Z22
	VSHUFI32X4   $0xee, Z10, Z23, Z23
	VSHUFI32X4   $0x44, Z11, Z24, Z10
	VSHUFI32X4   $0xee, Z11, Z24, Z24
	VSHUFI32X4   $0x44, Z13, Z9, Z11
	VSHUFI32X4   $0xee, Z13, Z9, Z9
	VSHUFI32X4   $0x44, Z12, Z8, Z13
	VSHUFI32X4   $0xee, Z12, Z8, Z8
	VSHUFI32X4   $0x44, Z18, Z14, Z12
	VSHUFI32X4   $0xee, Z18, Z14, Z14
	VSHUFI32X4   $0x44, Z19, Z15, Z18
	VSHUFI32X4   $0xee, Z19, Z15, Z15
	VSHUFI32X4   $0x44, Z21, Z17, Z19
	VSHUFI32X4   $0xee, Z21, Z17, Z17
	VSHUFI32X4   $0x44, Z20, Z16, Z21
	VSHUFI32X4   $0xee, Z20, Z16, Z16
	VSHUFI32X4   $0x88, Z12, Z22, Z20
	VSHUFI32X4   $0xdd, Z12, Z22, Z22
	VSHUFI32X4   $0x88, Z18, Z10, Z12
	VSHUFI32X4   $0xdd, Z18, Z10, Z10
	VSHUFI32X4   $0x88, Z19, Z11, Z18
	VSHUFI32X4   $0xdd, Z19, Z11, Z11
	VSHUFI32X4   $0x88, Z21, Z13, Z19
	VSHUFI32X4   $0xdd, Z21, Z13, Z13
	VSHUFI32X4   $0x88, Z14, Z23, Z21
	VSHUFI32X4   $0xdd, Z14, Z23, Z23
	VSHUFI32X4   $0x88, Z15, Z24, Z14
	VSHUFI32X4   $0xdd, Z15, Z24, Z24
	VSHUFI32X4   $0x88, Z17, Z9, Z15
	VSHUFI32X4   $0xdd, Z17, Z9, Z9
	VSHUFI32X4   $0x88, Z16, Z8, Z17
	VSHUFI32X4   $0xdd, Z16, Z8, Z8
	VPBROADCASTD BX, Z16
	VPBROADCASTD SI, Z25
	VPBROADCASTD DI, Z26
	VPBROADCASTD R8, Z27
	VPBROADCASTD R9, Z28
	VPBROADCASTD R10, Z29
	VPBROADCASTD R11, Z30
	VPBROADCASTD R12, Z31
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z20, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z12, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z18, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z19, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z22, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z10, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z11, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z13, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z21, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z14, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z15, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z17, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z23, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z24, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z9, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z8, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z18, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z11, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z19, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z15, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z13, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z20, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z22, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z24, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z12, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z17, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z23, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z10, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z14, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z9, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z8, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z21, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z19, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z22, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z15, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z23, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z24, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z18, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z13, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z9, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z11, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z10, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z14, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z20, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z17, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z8, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z21, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z12, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z15, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z13, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z23, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z14, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z9, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z19, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z24, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z8, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z22, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z20, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z17, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z18, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z10, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z21, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z12, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z11, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z23, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z24, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z14, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z17, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z8, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z15, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z9, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z21, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z13, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z18, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z10, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z19, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z20, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z12, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z11, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z22, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z14, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z9, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z17, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z10, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z21, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z23, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z8, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z12, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z24, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z19, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z20, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z15, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z18, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z11, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z22, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z13, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z17, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z8, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z10, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z20, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z12, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z14, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z21, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z11, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z9, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z15, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z18, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z23, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z19, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z22, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z13, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z24, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x07, Z4, Z4
	VPXORD       Z0, Z16, Z0
	VPXORD       Z1, Z25, Z1
	VPXORD       Z2, Z26, Z2
	VPXORD       Z3, Z27, Z3
	VPXORD       Z4, Z28, Z4
	VPXORD       Z5, Z29, Z5
	VPXORD       Z6, Z30, Z6
	VPXORD       Z7, Z31, Z7
	CMPQ         DX, $0x00001000
	JNE          loopStart
	VSHUFPS      $0x44, Z1, Z0, Z8
	VSHUFPS      $0xee, Z1, Z0, Z0
	VSHUFPS      $0x44, Z3, Z2, Z1
	VSHUFPS      $0xee, Z3, Z2, Z2
	VSHUFPS      $0x44, Z5, Z4, Z3
	VSHUFPS      $0xee, Z5, Z4, Z4
	VSHUFPS      $0x44, Z7, Z6, Z5
	VSHUFPS      $0xee, Z7, Z6, Z6
	VSHUFPS      $0x88, Z1, Z8, Z7
	VSHUFPS      $0xdd, Z1, Z8, Z8
	VSHUFPS      $0x88, Z2, Z0, Z1
	VSHUFPS      $0xdd, Z2, Z0, Z0
	VSHUFPS      $0x88, Z5, Z3, Z2
	VSHUFPS      $0xdd, Z5, Z3, Z3
	VSHUFPS      $0x88, Z6, Z4, Z5
	VSHUFPS      $0xdd, Z6, Z4, Z4
	VSHUFI32X4   $0x44, Z2, Z7, Z6
	VSHUFI32X4   $0xee, Z2, Z7, Z7
	VSHUFI32X4   $0x44, Z3, Z8, Z2
	VSHUFI32X4   $0xee, Z3, Z8, Z8
	VSHUFI32X4   $0x44, Z5, Z1, Z3
	VSHUFI32X4   $0xee, Z5, Z1, Z1
	VSHUFI32X4   $0x44, Z4, Z0, Z5
	VSHUFI32X4   $0xee, Z4, Z0, Z0
	VSHUFI32X4   $0x88, Z2, Z6, Z4
	VSHUFI32X4   $0xdd, Z2, Z6, Z6
	VSHUFI32X4   $0x88, Z5, Z3, Z2
	VSHUFI32X4   $0xdd, Z5, Z3, Z3
	VSHUFI32X4   $0x88, Z8, Z7, Z5
	VSHUFI32X4   $0xdd, Z8, Z7, Z7
	VSHUFI32X4   $0x88, Z0, Z1, Z8
	VSHUFI32X4   $0xdd, Z0, Z1, Z1
	MOVQ         hashes+8(FP), AX
	TESTW        $0x0001, CX
	JZ           noHash0
	MOVQ         (AX), DX
	VMOVDQU64    Y4, (DX)

noHash0:
	TESTW      $0x0002, CX
	JZ         noHash1
	VSHUFI32X4 $0xee, Z4, Z4, Z4
	MOVQ       8(AX), DX
	VMOVDQU64  Y4, (DX)

noHash1:
	TESTW     $0x0004, CX
	JZ        noHash2
	MOVQ      16(AX), DX
	VMOVDQU64 Y2, (DX)

noHash2:
	TESTW      $0x0008, CX
	JZ         noHash3
	VSHUFI32X4 $0xee, Z2, Z2, Z2
	MOVQ       24(AX), DX
	VMOVDQU64  Y2, (DX)

noHash3:
	TESTW     $0x0010, CX
	JZ        noHash4
	MOVQ      32(AX), DX
	VMOVDQU64 Y6, (DX)

noHash4:
	TESTW      $0x0020, CX
	JZ         noHash5
	VSHUFI32X4 $0xee, Z6, Z6, Z6
	MOVQ       40(AX), DX
	VMOVDQU64  Y6, (DX)

noHash5:
	TESTW     $0x0040, CX
	JZ        noHash6
	MOVQ      48(AX), DX
	VMOVDQU64 Y3, (DX)

noHash6:
	TESTW      $0x0080, CX
	JZ         noHash7
	VSHUFI32X4 $0xee, Z3, Z3, Z3
	MOVQ       56(AX), DX
	VMOVDQU64  Y3, (DX)

noHash7:
	TESTW     $0x0100, CX
	JZ        noHash8
	MOVQ      64(AX), DX
	VMOVDQU64 Y5, (DX)

noHash8:
	TESTW      $0x0200, CX
	JZ         noHash9
	VSHUFI32X4 $0xee, Z5, Z5, Z5
	MOVQ       72(AX), DX
	VMOVDQU64  Y5, (DX)

noHash9:
	TESTW     $0x0400, CX
	JZ        noHash10
	MOVQ      80(AX), DX
	VMOVDQU64 Y8, (DX)

noHash10:
	TESTW      $0x0800, CX
	JZ         noHash11
	VSHUFI32X4 $0xee, Z8, Z8, Z8
	MOVQ       88(AX), DX
	VMOVDQU64  Y8, (DX)

noHash11:
	TESTW     $0x1000, CX
	JZ        noHash12
	MOVQ      96(AX), DX
	VMOVDQU64 Y7, (DX)

noHash12:
	TESTW      $0x2000, CX
	JZ         noHash13
	VSHUFI32X4 $0xee, Z7, Z7, Z7
	MOVQ       104(AX), DX
	VMOVDQU64  Y7, (DX)

noHash13:
	TESTW     $0x4000, CX
	JZ        noHash14
	MOVQ      112(AX), DX
	VMOVDQU64 Y1, (DX)

noHash14:
	TESTW      $0x8000, CX
	JZ         noHash15
	VSHUFI32X4 $0xee, Z1, Z1, Z1
	MOVQ       120(AX), DX
	VMOVDQU64  Y1, (DX)

noHash15:
	RET

// func Blake32048(blocks **byte, hashes **byte, mask uint16)
// Requires: AVX512BW, AVX512F, AVX512VL
TEXT ·Blake32048(SB), NOSPLIT, $0-18
	MOVQ         blocks+0(FP), AX
	MOVW         mask+16(FP), CX
	XORQ         DX, DX
	MOVD         $0x6a09e667, BX
	VPBROADCASTD BX, Z0
	MOVD         $0xbb67ae85, BX
	VPBROADCASTD BX, Z1
	MOVD         $0x3c6ef372, BX
	VPBROADCASTD BX, Z2
	MOVD         $0xa54ff53a, BX
	VPBROADCASTD BX, Z3
	MOVD         $0x510e527f, BX
	VPBROADCASTD BX, Z4
	MOVD         $0x9b05688c, BX
	VPBROADCASTD BX, Z5
	MOVD         $0x1f83d9ab, BX
	VPBROADCASTD BX, Z6
	MOVD         $0x5be0cd19, BX
	VPBROADCASTD BX, Z7
	MOVD         $0x6a09e667, BX
	MOVD         $0xbb67ae85, SI
	MOVD         $0x3c6ef372, DI
	MOVD         $0xa54ff53a, R8
	MOVD         $0x00000000, R9
	MOVD         $0x00000000, R10
	MOVD         $0x00000040, R11
	MOVD         $0x00000000, R12

loopStart:
	VPBROADCASTW CX, Z8
	TESTW        $0x0001, CX
	JZ           loadEnd0
	MOVQ         (AX), R13
	VMOVDQA64    (R13), Z8

loadEnd0:
	VPBROADCASTW CX, Z9
	TESTW        $0x0002, CX
	JZ           loadEnd1
	MOVQ         8(AX), R13
	VMOVDQA64    (R13), Z9

loadEnd1:
	VPBROADCASTW CX, Z10
	TESTW        $0x0004, CX
	JZ           loadEnd2
	MOVQ         16(AX), R13
	VMOVDQA64    (R13), Z10

loadEnd2:
	VPBROADCASTW CX, Z11
	TESTW        $0x0008, CX
	JZ           loadEnd3
	MOVQ         24(AX), R13
	VMOVDQA64    (R13), Z11

loadEnd3:
	VPBROADCASTW CX, Z12
	TESTW        $0x0010, CX
	JZ           loadEnd4
	MOVQ         32(AX), R13
	VMOVDQA64    (R13), Z12

loadEnd4:
	VPBROADCASTW CX, Z13
	TESTW        $0x0020, CX
	JZ           loadEnd5
	MOVQ         40(AX), R13
	VMOVDQA64    (R13), Z13

loadEnd5:
	VPBROADCASTW CX, Z14
	TESTW        $0x0040, CX
	JZ           loadEnd6
	MOVQ         48(AX), R13
	VMOVDQA64    (R13), Z14

loadEnd6:
	VPBROADCASTW CX, Z15
	TESTW        $0x0080, CX
	JZ           loadEnd7
	MOVQ         56(AX), R13
	VMOVDQA64    (R13), Z15

loadEnd7:
	VPBROADCASTW CX, Z16
	TESTW        $0x0100, CX
	JZ           loadEnd8
	MOVQ         64(AX), R13
	VMOVDQA64    (R13), Z16

loadEnd8:
	VPBROADCASTW CX, Z17
	TESTW        $0x0200, CX
	JZ           loadEnd9
	MOVQ         72(AX), R13
	VMOVDQA64    (R13), Z17

loadEnd9:
	VPBROADCASTW CX, Z18
	TESTW        $0x0400, CX
	JZ           loadEnd10
	MOVQ         80(AX), R13
	VMOVDQA64    (R13), Z18

loadEnd10:
	VPBROADCASTW CX, Z19
	TESTW        $0x0800, CX
	JZ           loadEnd11
	MOVQ         88(AX), R13
	VMOVDQA64    (R13), Z19

loadEnd11:
	VPBROADCASTW CX, Z20
	TESTW        $0x1000, CX
	JZ           loadEnd12
	MOVQ         96(AX), R13
	VMOVDQA64    (R13), Z20

loadEnd12:
	VPBROADCASTW CX, Z21
	TESTW        $0x2000, CX
	JZ           loadEnd13
	MOVQ         104(AX), R13
	VMOVDQA64    (R13), Z21

loadEnd13:
	VPBROADCASTW CX, Z22
	TESTW        $0x4000, CX
	JZ           loadEnd14
	MOVQ         112(AX), R13
	VMOVDQA64    (R13), Z22

loadEnd14:
	VPBROADCASTW CX, Z23
	TESTW        $0x8000, CX
	JZ           loadEnd15
	MOVQ         120(AX), R13
	VMOVDQA64    (R13), Z23

loadEnd15:
	ADDQ         $0x40, DX
	VSHUFPS      $0x44, Z9, Z8, Z24
	VSHUFPS      $0xee, Z9, Z8, Z8
	VSHUFPS      $0x44, Z11, Z10, Z9
	VSHUFPS      $0xee, Z11, Z10, Z10
	VSHUFPS      $0x44, Z13, Z12, Z11
	VSHUFPS      $0xee, Z13, Z12, Z12
	VSHUFPS      $0x44, Z15, Z14, Z13
	VSHUFPS      $0xee, Z15, Z14, Z14
	VSHUFPS      $0x44, Z17, Z16, Z15
	VSHUFPS      $0xee, Z17, Z16, Z16
	VSHUFPS      $0x44, Z19, Z18, Z17
	VSHUFPS      $0xee, Z19, Z18, Z18
	VSHUFPS      $0x44, Z21, Z20, Z19
	VSHUFPS      $0xee, Z21, Z20, Z20
	VSHUFPS      $0x44, Z23, Z22, Z21
	VSHUFPS      $0xee, Z23, Z22, Z22
	VSHUFPS      $0x88, Z9, Z24, Z23
	VSHUFPS      $0xdd, Z9, Z24, Z24
	VSHUFPS      $0x88, Z10, Z8, Z9
	VSHUFPS      $0xdd, Z10, Z8, Z8
	VSHUFPS      $0x88, Z13, Z11, Z10
	VSHUFPS      $0xdd, Z13, Z11, Z11
	VSHUFPS      $0x88, Z14, Z12, Z13
	VSHUFPS      $0xdd, Z14, Z12, Z12
	VSHUFPS      $0x88, Z17, Z15, Z14
	VSHUFPS      $0xdd, Z17, Z15, Z15
	VSHUFPS      $0x88, Z18, Z16, Z17
	VSHUFPS      $0xdd, Z18, Z16, Z16
	VSHUFPS      $0x88, Z21, Z19, Z18
	VSHUFPS      $0xdd, Z21, Z19, Z19
	VSHUFPS      $0x88, Z22, Z20, Z21
	VSHUFPS      $0xdd, Z22, Z20, Z20
	VSHUFI32X4   $0x44, Z10, Z23, Z22
	VSHUFI32X4   $0xee, Z10, Z23, Z23
	VSHUFI32X4   $0x44, Z11, Z24, Z10
	VSHUFI32X4   $0xee, Z11, Z24, Z24
	VSHUFI32X4   $0x44, Z13, Z9, Z11
	VSHUFI32X4   $0xee, Z13, Z9, Z9
	VSHUFI32X4   $0x44, Z12, Z8, Z13
	VSHUFI32X4   $0xee, Z12, Z8, Z8
	VSHUFI32X4   $0x44, Z18, Z14, Z12
	VSHUFI32X4   $0xee, Z18, Z14, Z14
	VSHUFI32X4   $0x44, Z19, Z15, Z18
	VSHUFI32X4   $0xee, Z19, Z15, Z15
	VSHUFI32X4   $0x44, Z21, Z17, Z19
	VSHUFI32X4   $0xee, Z21, Z17, Z17
	VSHUFI32X4   $0x44, Z20, Z16, Z21
	VSHUFI32X4   $0xee, Z20, Z16, Z16
	VSHUFI32X4   $0x88, Z12, Z22, Z20
	VSHUFI32X4   $0xdd, Z12, Z22, Z22
	VSHUFI32X4   $0x88, Z18, Z10, Z12
	VSHUFI32X4   $0xdd, Z18, Z10, Z10
	VSHUFI32X4   $0x88, Z19, Z11, Z18
	VSHUFI32X4   $0xdd, Z19, Z11, Z11
	VSHUFI32X4   $0x88, Z21, Z13, Z19
	VSHUFI32X4   $0xdd, Z21, Z13, Z13
	VSHUFI32X4   $0x88, Z14, Z23, Z21
	VSHUFI32X4   $0xdd, Z14, Z23, Z23
	VSHUFI32X4   $0x88, Z15, Z24, Z14
	VSHUFI32X4   $0xdd, Z15, Z24, Z24
	VSHUFI32X4   $0x88, Z17, Z9, Z15
	VSHUFI32X4   $0xdd, Z17, Z9, Z9
	VSHUFI32X4   $0x88, Z16, Z8, Z17
	VSHUFI32X4   $0xdd, Z16, Z8, Z8
	VPBROADCASTD BX, Z16
	VPBROADCASTD SI, Z25
	VPBROADCASTD DI, Z26
	VPBROADCASTD R8, Z27
	VPBROADCASTD R9, Z28
	VPBROADCASTD R10, Z29
	VPBROADCASTD R11, Z30
	VPBROADCASTD R12, Z31
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z20, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z12, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z18, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z19, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z22, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z10, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z11, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z13, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z21, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z14, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z15, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z17, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z23, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z24, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z9, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z8, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z18, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z11, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z19, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z15, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z13, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z20, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z22, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z24, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z12, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z17, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z23, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z10, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z14, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z9, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z8, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z21, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z19, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z22, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z15, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z23, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z24, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z18, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z13, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z9, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z11, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z10, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z14, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z20, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z17, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z8, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z21, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z12, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z15, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z13, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z23, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z14, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z9, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z19, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z24, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z8, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z22, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z20, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z17, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z18, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z10, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z21, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z12, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z11, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z23, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z24, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z14, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z17, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z8, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z15, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z9, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z21, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z13, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z18, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z10, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z19, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z20, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z12, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z11, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z22, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z14, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z9, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z17, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z10, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z21, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z23, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z8, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z12, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z24, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z19, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z20, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z15, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z18, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z11, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z22, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z13, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z17, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z8, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z10, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z20, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z12, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z14, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z21, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z11, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z9, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z15, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z18, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z23, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z19, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z22, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z13, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z24, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x07, Z4, Z4
	VPXORD       Z0, Z16, Z0
	VPXORD       Z1, Z25, Z1
	VPXORD       Z2, Z26, Z2
	VPXORD       Z3, Z27, Z3
	VPXORD       Z4, Z28, Z4
	VPXORD       Z5, Z29, Z5
	VPXORD       Z6, Z30, Z6
	VPXORD       Z7, Z31, Z7
	CMPQ         DX, $0x00000800
	JNE          loopStart
	VSHUFPS      $0x44, Z1, Z0, Z8
	VSHUFPS      $0xee, Z1, Z0, Z0
	VSHUFPS      $0x44, Z3, Z2, Z1
	VSHUFPS      $0xee, Z3, Z2, Z2
	VSHUFPS      $0x44, Z5, Z4, Z3
	VSHUFPS      $0xee, Z5, Z4, Z4
	VSHUFPS      $0x44, Z7, Z6, Z5
	VSHUFPS      $0xee, Z7, Z6, Z6
	VSHUFPS      $0x88, Z1, Z8, Z7
	VSHUFPS      $0xdd, Z1, Z8, Z8
	VSHUFPS      $0x88, Z2, Z0, Z1
	VSHUFPS      $0xdd, Z2, Z0, Z0
	VSHUFPS      $0x88, Z5, Z3, Z2
	VSHUFPS      $0xdd, Z5, Z3, Z3
	VSHUFPS      $0x88, Z6, Z4, Z5
	VSHUFPS      $0xdd, Z6, Z4, Z4
	VSHUFI32X4   $0x44, Z2, Z7, Z6
	VSHUFI32X4   $0xee, Z2, Z7, Z7
	VSHUFI32X4   $0x44, Z3, Z8, Z2
	VSHUFI32X4   $0xee, Z3, Z8, Z8
	VSHUFI32X4   $0x44, Z5, Z1, Z3
	VSHUFI32X4   $0xee, Z5, Z1, Z1
	VSHUFI32X4   $0x44, Z4, Z0, Z5
	VSHUFI32X4   $0xee, Z4, Z0, Z0
	VSHUFI32X4   $0x88, Z2, Z6, Z4
	VSHUFI32X4   $0xdd, Z2, Z6, Z6
	VSHUFI32X4   $0x88, Z5, Z3, Z2
	VSHUFI32X4   $0xdd, Z5, Z3, Z3
	VSHUFI32X4   $0x88, Z8, Z7, Z5
	VSHUFI32X4   $0xdd, Z8, Z7, Z7
	VSHUFI32X4   $0x88, Z0, Z1, Z8
	VSHUFI32X4   $0xdd, Z0, Z1, Z1
	MOVQ         hashes+8(FP), AX
	TESTW        $0x0001, CX
	JZ           noHash0
	MOVQ         (AX), DX
	VMOVDQU64    Y4, (DX)

noHash0:
	TESTW      $0x0002, CX
	JZ         noHash1
	VSHUFI32X4 $0xee, Z4, Z4, Z4
	MOVQ       8(AX), DX
	VMOVDQU64  Y4, (DX)

noHash1:
	TESTW     $0x0004, CX
	JZ        noHash2
	MOVQ      16(AX), DX
	VMOVDQU64 Y2, (DX)

noHash2:
	TESTW      $0x0008, CX
	JZ         noHash3
	VSHUFI32X4 $0xee, Z2, Z2, Z2
	MOVQ       24(AX), DX
	VMOVDQU64  Y2, (DX)

noHash3:
	TESTW     $0x0010, CX
	JZ        noHash4
	MOVQ      32(AX), DX
	VMOVDQU64 Y6, (DX)

noHash4:
	TESTW      $0x0020, CX
	JZ         noHash5
	VSHUFI32X4 $0xee, Z6, Z6, Z6
	MOVQ       40(AX), DX
	VMOVDQU64  Y6, (DX)

noHash5:
	TESTW     $0x0040, CX
	JZ        noHash6
	MOVQ      48(AX), DX
	VMOVDQU64 Y3, (DX)

noHash6:
	TESTW      $0x0080, CX
	JZ         noHash7
	VSHUFI32X4 $0xee, Z3, Z3, Z3
	MOVQ       56(AX), DX
	VMOVDQU64  Y3, (DX)

noHash7:
	TESTW     $0x0100, CX
	JZ        noHash8
	MOVQ      64(AX), DX
	VMOVDQU64 Y5, (DX)

noHash8:
	TESTW      $0x0200, CX
	JZ         noHash9
	VSHUFI32X4 $0xee, Z5, Z5, Z5
	MOVQ       72(AX), DX
	VMOVDQU64  Y5, (DX)

noHash9:
	TESTW     $0x0400, CX
	JZ        noHash10
	MOVQ      80(AX), DX
	VMOVDQU64 Y8, (DX)

noHash10:
	TESTW      $0x0800, CX
	JZ         noHash11
	VSHUFI32X4 $0xee, Z8, Z8, Z8
	MOVQ       88(AX), DX
	VMOVDQU64  Y8, (DX)

noHash11:
	TESTW     $0x1000, CX
	JZ        noHash12
	MOVQ      96(AX), DX
	VMOVDQU64 Y7, (DX)

noHash12:
	TESTW      $0x2000, CX
	JZ         noHash13
	VSHUFI32X4 $0xee, Z7, Z7, Z7
	MOVQ       104(AX), DX
	VMOVDQU64  Y7, (DX)

noHash13:
	TESTW     $0x4000, CX
	JZ        noHash14
	MOVQ      112(AX), DX
	VMOVDQU64 Y1, (DX)

noHash14:
	TESTW      $0x8000, CX
	JZ         noHash15
	VSHUFI32X4 $0xee, Z1, Z1, Z1
	MOVQ       120(AX), DX
	VMOVDQU64  Y1, (DX)

noHash15:
	RET
