// Code generated by command: go run avo.go -out ../asm.s -stubs ../asm_stub.go -pkg hash. DO NOT EDIT.

#include "textflag.h"

// func Blake3AndCopy4096(blocks **byte, copy **byte, hash1 **byte, hash2 **byte, mask uint32)
// Requires: AVX512F, AVX512VL
TEXT ·Blake3AndCopy4096(SB), NOSPLIT, $0-36
	MOVQ         blocks+0(FP), AX
	MOVQ         copy+8(FP), CX
	MOVL         mask+32(FP), DX
	XORQ         BX, BX
	MOVD         $0x6a09e667, SI
	VPBROADCASTD SI, Z0
	MOVD         $0xbb67ae85, SI
	VPBROADCASTD SI, Z1
	MOVD         $0x3c6ef372, SI
	VPBROADCASTD SI, Z2
	MOVD         $0xa54ff53a, SI
	VPBROADCASTD SI, Z3
	MOVD         $0x510e527f, SI
	VPBROADCASTD SI, Z4
	MOVD         $0x9b05688c, SI
	VPBROADCASTD SI, Z5
	MOVD         $0x1f83d9ab, SI
	VPBROADCASTD SI, Z6
	MOVD         $0x5be0cd19, SI
	VPBROADCASTD SI, Z7
	MOVD         $0x6a09e667, SI
	MOVD         $0xbb67ae85, DI
	MOVD         $0x3c6ef372, R8
	MOVD         $0xa54ff53a, R9
	MOVD         $0x00000000, R10
	MOVD         $0x00000000, R11
	MOVD         $0x00000040, R12
	MOVD         $0x00000000, R13

loopStart:
	VPBROADCASTD DX, Z8
	TESTL        $0x00010000, DX
	JZ           copyEnd0
	MOVQ         (AX), R14
	VMOVDQA64    (R14), Z8
	TESTL        $0x00000001, DX
	JZ           copyEnd0
	MOVQ         (CX), R14
	ADDQ         BX, R14
	VMOVDQA64    Z8, (R14)

copyEnd0:
	VPBROADCASTD DX, Z9
	TESTL        $0x00020000, DX
	JZ           copyEnd1
	MOVQ         8(AX), R14
	VMOVDQA64    (R14), Z9
	TESTL        $0x00000002, DX
	JZ           copyEnd1
	MOVQ         8(CX), R14
	ADDQ         BX, R14
	VMOVDQA64    Z9, (R14)

copyEnd1:
	VPBROADCASTD DX, Z10
	TESTL        $0x00040000, DX
	JZ           copyEnd2
	MOVQ         16(AX), R14
	VMOVDQA64    (R14), Z10
	TESTL        $0x00000004, DX
	JZ           copyEnd2
	MOVQ         16(CX), R14
	ADDQ         BX, R14
	VMOVDQA64    Z10, (R14)

copyEnd2:
	VPBROADCASTD DX, Z11
	TESTL        $0x00080000, DX
	JZ           copyEnd3
	MOVQ         24(AX), R14
	VMOVDQA64    (R14), Z11
	TESTL        $0x00000008, DX
	JZ           copyEnd3
	MOVQ         24(CX), R14
	ADDQ         BX, R14
	VMOVDQA64    Z11, (R14)

copyEnd3:
	VPBROADCASTD DX, Z12
	TESTL        $0x00100000, DX
	JZ           copyEnd4
	MOVQ         32(AX), R14
	VMOVDQA64    (R14), Z12
	TESTL        $0x00000010, DX
	JZ           copyEnd4
	MOVQ         32(CX), R14
	ADDQ         BX, R14
	VMOVDQA64    Z12, (R14)

copyEnd4:
	VPBROADCASTD DX, Z13
	TESTL        $0x00200000, DX
	JZ           copyEnd5
	MOVQ         40(AX), R14
	VMOVDQA64    (R14), Z13
	TESTL        $0x00000020, DX
	JZ           copyEnd5
	MOVQ         40(CX), R14
	ADDQ         BX, R14
	VMOVDQA64    Z13, (R14)

copyEnd5:
	VPBROADCASTD DX, Z14
	TESTL        $0x00400000, DX
	JZ           copyEnd6
	MOVQ         48(AX), R14
	VMOVDQA64    (R14), Z14
	TESTL        $0x00000040, DX
	JZ           copyEnd6
	MOVQ         48(CX), R14
	ADDQ         BX, R14
	VMOVDQA64    Z14, (R14)

copyEnd6:
	VPBROADCASTD DX, Z15
	TESTL        $0x00800000, DX
	JZ           copyEnd7
	MOVQ         56(AX), R14
	VMOVDQA64    (R14), Z15
	TESTL        $0x00000080, DX
	JZ           copyEnd7
	MOVQ         56(CX), R14
	ADDQ         BX, R14
	VMOVDQA64    Z15, (R14)

copyEnd7:
	VPBROADCASTD DX, Z16
	TESTL        $0x01000000, DX
	JZ           copyEnd8
	MOVQ         64(AX), R14
	VMOVDQA64    (R14), Z16
	TESTL        $0x00000100, DX
	JZ           copyEnd8
	MOVQ         64(CX), R14
	ADDQ         BX, R14
	VMOVDQA64    Z16, (R14)

copyEnd8:
	VPBROADCASTD DX, Z17
	TESTL        $0x02000000, DX
	JZ           copyEnd9
	MOVQ         72(AX), R14
	VMOVDQA64    (R14), Z17
	TESTL        $0x00000200, DX
	JZ           copyEnd9
	MOVQ         72(CX), R14
	ADDQ         BX, R14
	VMOVDQA64    Z17, (R14)

copyEnd9:
	VPBROADCASTD DX, Z18
	TESTL        $0x04000000, DX
	JZ           copyEnd10
	MOVQ         80(AX), R14
	VMOVDQA64    (R14), Z18
	TESTL        $0x00000400, DX
	JZ           copyEnd10
	MOVQ         80(CX), R14
	ADDQ         BX, R14
	VMOVDQA64    Z18, (R14)

copyEnd10:
	VPBROADCASTD DX, Z19
	TESTL        $0x08000000, DX
	JZ           copyEnd11
	MOVQ         88(AX), R14
	VMOVDQA64    (R14), Z19
	TESTL        $0x00000800, DX
	JZ           copyEnd11
	MOVQ         88(CX), R14
	ADDQ         BX, R14
	VMOVDQA64    Z19, (R14)

copyEnd11:
	VPBROADCASTD DX, Z20
	TESTL        $0x10000000, DX
	JZ           copyEnd12
	MOVQ         96(AX), R14
	VMOVDQA64    (R14), Z20
	TESTL        $0x00001000, DX
	JZ           copyEnd12
	MOVQ         96(CX), R14
	ADDQ         BX, R14
	VMOVDQA64    Z20, (R14)

copyEnd12:
	VPBROADCASTD DX, Z21
	TESTL        $0x20000000, DX
	JZ           copyEnd13
	MOVQ         104(AX), R14
	VMOVDQA64    (R14), Z21
	TESTL        $0x00002000, DX
	JZ           copyEnd13
	MOVQ         104(CX), R14
	ADDQ         BX, R14
	VMOVDQA64    Z21, (R14)

copyEnd13:
	VPBROADCASTD DX, Z22
	TESTL        $0x40000000, DX
	JZ           copyEnd14
	MOVQ         112(AX), R14
	VMOVDQA64    (R14), Z22
	TESTL        $0x00004000, DX
	JZ           copyEnd14
	MOVQ         112(CX), R14
	ADDQ         BX, R14
	VMOVDQA64    Z22, (R14)

copyEnd14:
	VPBROADCASTD DX, Z23
	TESTL        $0x80000000, DX
	JZ           copyEnd15
	MOVQ         120(AX), R14
	VMOVDQA64    (R14), Z23
	TESTL        $0x00008000, DX
	JZ           copyEnd15
	MOVQ         120(CX), R14
	ADDQ         BX, R14
	VMOVDQA64    Z23, (R14)

copyEnd15:
	ADDQ         $0x40, BX
	VSHUFPS      $0x44, Z9, Z8, Z24
	VSHUFPS      $0xee, Z9, Z8, Z8
	VSHUFPS      $0x44, Z11, Z10, Z9
	VSHUFPS      $0xee, Z11, Z10, Z10
	VSHUFPS      $0x44, Z13, Z12, Z11
	VSHUFPS      $0xee, Z13, Z12, Z12
	VSHUFPS      $0x44, Z15, Z14, Z13
	VSHUFPS      $0xee, Z15, Z14, Z14
	VSHUFPS      $0x44, Z17, Z16, Z15
	VSHUFPS      $0xee, Z17, Z16, Z16
	VSHUFPS      $0x44, Z19, Z18, Z17
	VSHUFPS      $0xee, Z19, Z18, Z18
	VSHUFPS      $0x44, Z21, Z20, Z19
	VSHUFPS      $0xee, Z21, Z20, Z20
	VSHUFPS      $0x44, Z23, Z22, Z21
	VSHUFPS      $0xee, Z23, Z22, Z22
	VSHUFPS      $0x88, Z9, Z24, Z23
	VSHUFPS      $0xdd, Z9, Z24, Z24
	VSHUFPS      $0x88, Z10, Z8, Z9
	VSHUFPS      $0xdd, Z10, Z8, Z8
	VSHUFPS      $0x88, Z13, Z11, Z10
	VSHUFPS      $0xdd, Z13, Z11, Z11
	VSHUFPS      $0x88, Z14, Z12, Z13
	VSHUFPS      $0xdd, Z14, Z12, Z12
	VSHUFPS      $0x88, Z17, Z15, Z14
	VSHUFPS      $0xdd, Z17, Z15, Z15
	VSHUFPS      $0x88, Z18, Z16, Z17
	VSHUFPS      $0xdd, Z18, Z16, Z16
	VSHUFPS      $0x88, Z21, Z19, Z18
	VSHUFPS      $0xdd, Z21, Z19, Z19
	VSHUFPS      $0x88, Z22, Z20, Z21
	VSHUFPS      $0xdd, Z22, Z20, Z20
	VSHUFI32X4   $0x44, Z10, Z23, Z22
	VSHUFI32X4   $0xee, Z10, Z23, Z23
	VSHUFI32X4   $0x44, Z11, Z24, Z10
	VSHUFI32X4   $0xee, Z11, Z24, Z24
	VSHUFI32X4   $0x44, Z13, Z9, Z11
	VSHUFI32X4   $0xee, Z13, Z9, Z9
	VSHUFI32X4   $0x44, Z12, Z8, Z13
	VSHUFI32X4   $0xee, Z12, Z8, Z8
	VSHUFI32X4   $0x44, Z18, Z14, Z12
	VSHUFI32X4   $0xee, Z18, Z14, Z14
	VSHUFI32X4   $0x44, Z19, Z15, Z18
	VSHUFI32X4   $0xee, Z19, Z15, Z15
	VSHUFI32X4   $0x44, Z21, Z17, Z19
	VSHUFI32X4   $0xee, Z21, Z17, Z17
	VSHUFI32X4   $0x44, Z20, Z16, Z21
	VSHUFI32X4   $0xee, Z20, Z16, Z16
	VSHUFI32X4   $0x88, Z12, Z22, Z20
	VSHUFI32X4   $0xdd, Z12, Z22, Z22
	VSHUFI32X4   $0x88, Z18, Z10, Z12
	VSHUFI32X4   $0xdd, Z18, Z10, Z10
	VSHUFI32X4   $0x88, Z19, Z11, Z18
	VSHUFI32X4   $0xdd, Z19, Z11, Z11
	VSHUFI32X4   $0x88, Z21, Z13, Z19
	VSHUFI32X4   $0xdd, Z21, Z13, Z13
	VSHUFI32X4   $0x88, Z14, Z23, Z21
	VSHUFI32X4   $0xdd, Z14, Z23, Z23
	VSHUFI32X4   $0x88, Z15, Z24, Z14
	VSHUFI32X4   $0xdd, Z15, Z24, Z24
	VSHUFI32X4   $0x88, Z17, Z9, Z15
	VSHUFI32X4   $0xdd, Z17, Z9, Z9
	VSHUFI32X4   $0x88, Z16, Z8, Z17
	VSHUFI32X4   $0xdd, Z16, Z8, Z8
	VPBROADCASTD SI, Z16
	VPBROADCASTD DI, Z25
	VPBROADCASTD R8, Z26
	VPBROADCASTD R9, Z27
	VPBROADCASTD R10, Z28
	VPBROADCASTD R11, Z29
	VPBROADCASTD R12, Z30
	VPBROADCASTD R13, Z31
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z20, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z12, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z18, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z19, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z22, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z10, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z11, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z13, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z21, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z14, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z15, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z17, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z23, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z24, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z9, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z8, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z18, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z11, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z19, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z15, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z13, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z20, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z22, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z24, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z12, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z17, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z23, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z10, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z14, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z9, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z8, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z21, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z19, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z22, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z15, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z23, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z24, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z18, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z13, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z9, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z11, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z10, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z14, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z20, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z17, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z8, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z21, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z12, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z15, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z13, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z23, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z14, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z9, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z19, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z24, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z8, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z22, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z20, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z17, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z18, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z10, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z21, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z12, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z11, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z23, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z24, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z14, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z17, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z8, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z15, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z9, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z21, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z13, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z18, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z10, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z19, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z20, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z12, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z11, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z22, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z14, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z9, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z17, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z10, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z21, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z23, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z8, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z12, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z24, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z19, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z20, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z15, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z18, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z11, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z22, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z13, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z17, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z8, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z10, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z20, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z12, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z14, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z21, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z11, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z9, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z15, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z18, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z23, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z19, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z22, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z13, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z24, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x07, Z4, Z4
	VPXORD       Z0, Z16, Z0
	VPXORD       Z1, Z25, Z1
	VPXORD       Z2, Z26, Z2
	VPXORD       Z3, Z27, Z3
	VPXORD       Z4, Z28, Z4
	VPXORD       Z5, Z29, Z5
	VPXORD       Z6, Z30, Z6
	VPXORD       Z7, Z31, Z7
	CMPQ         BX, $0x00001000
	JNE          loopStart
	VSHUFPS      $0x44, Z1, Z0, Z8
	VSHUFPS      $0xee, Z1, Z0, Z0
	VSHUFPS      $0x44, Z3, Z2, Z1
	VSHUFPS      $0xee, Z3, Z2, Z2
	VSHUFPS      $0x44, Z5, Z4, Z3
	VSHUFPS      $0xee, Z5, Z4, Z4
	VSHUFPS      $0x44, Z7, Z6, Z5
	VSHUFPS      $0xee, Z7, Z6, Z6
	VSHUFPS      $0x88, Z1, Z8, Z7
	VSHUFPS      $0xdd, Z1, Z8, Z8
	VSHUFPS      $0x88, Z2, Z0, Z1
	VSHUFPS      $0xdd, Z2, Z0, Z0
	VSHUFPS      $0x88, Z5, Z3, Z2
	VSHUFPS      $0xdd, Z5, Z3, Z3
	VSHUFPS      $0x88, Z6, Z4, Z5
	VSHUFPS      $0xdd, Z6, Z4, Z4
	VSHUFI32X4   $0x44, Z2, Z7, Z6
	VSHUFI32X4   $0xee, Z2, Z7, Z7
	VSHUFI32X4   $0x44, Z3, Z8, Z2
	VSHUFI32X4   $0xee, Z3, Z8, Z8
	VSHUFI32X4   $0x44, Z5, Z1, Z3
	VSHUFI32X4   $0xee, Z5, Z1, Z1
	VSHUFI32X4   $0x44, Z4, Z0, Z5
	VSHUFI32X4   $0xee, Z4, Z0, Z0
	VSHUFI32X4   $0x88, Z2, Z6, Z4
	VSHUFI32X4   $0xdd, Z2, Z6, Z6
	VSHUFI32X4   $0x88, Z5, Z3, Z2
	VSHUFI32X4   $0xdd, Z5, Z3, Z3
	VSHUFI32X4   $0x88, Z8, Z7, Z5
	VSHUFI32X4   $0xdd, Z8, Z7, Z7
	VSHUFI32X4   $0x88, Z0, Z1, Z8
	VSHUFI32X4   $0xdd, Z0, Z1, Z1
	MOVQ         hash1+16(FP), AX
	MOVQ         hash2+24(FP), CX
	TESTL        $0x00010000, DX
	JZ           noHash0
	MOVQ         (AX), BX
	VMOVDQA64    Y4, (BX)
	MOVQ         (CX), BX
	VMOVDQU64    Y4, (BX)

noHash0:
	TESTL      $0x00020000, DX
	JZ         noHash1
	VSHUFI32X4 $0xee, Z4, Z4, Z4
	MOVQ       8(AX), BX
	VMOVDQA64  Y4, (BX)
	MOVQ       8(CX), BX
	VMOVDQU64  Y4, (BX)

noHash1:
	TESTL     $0x00040000, DX
	JZ        noHash2
	MOVQ      16(AX), BX
	VMOVDQA64 Y2, (BX)
	MOVQ      16(CX), BX
	VMOVDQU64 Y2, (BX)

noHash2:
	TESTL      $0x00080000, DX
	JZ         noHash3
	VSHUFI32X4 $0xee, Z2, Z2, Z2
	MOVQ       24(AX), BX
	VMOVDQA64  Y2, (BX)
	MOVQ       24(CX), BX
	VMOVDQU64  Y2, (BX)

noHash3:
	TESTL     $0x00100000, DX
	JZ        noHash4
	MOVQ      32(AX), BX
	VMOVDQA64 Y6, (BX)
	MOVQ      32(CX), BX
	VMOVDQU64 Y6, (BX)

noHash4:
	TESTL      $0x00200000, DX
	JZ         noHash5
	VSHUFI32X4 $0xee, Z6, Z6, Z6
	MOVQ       40(AX), BX
	VMOVDQA64  Y6, (BX)
	MOVQ       40(CX), BX
	VMOVDQU64  Y6, (BX)

noHash5:
	TESTL     $0x00400000, DX
	JZ        noHash6
	MOVQ      48(AX), BX
	VMOVDQA64 Y3, (BX)
	MOVQ      48(CX), BX
	VMOVDQU64 Y3, (BX)

noHash6:
	TESTL      $0x00800000, DX
	JZ         noHash7
	VSHUFI32X4 $0xee, Z3, Z3, Z3
	MOVQ       56(AX), BX
	VMOVDQA64  Y3, (BX)
	MOVQ       56(CX), BX
	VMOVDQU64  Y3, (BX)

noHash7:
	TESTL     $0x01000000, DX
	JZ        noHash8
	MOVQ      64(AX), BX
	VMOVDQA64 Y5, (BX)
	MOVQ      64(CX), BX
	VMOVDQU64 Y5, (BX)

noHash8:
	TESTL      $0x02000000, DX
	JZ         noHash9
	VSHUFI32X4 $0xee, Z5, Z5, Z5
	MOVQ       72(AX), BX
	VMOVDQA64  Y5, (BX)
	MOVQ       72(CX), BX
	VMOVDQU64  Y5, (BX)

noHash9:
	TESTL     $0x04000000, DX
	JZ        noHash10
	MOVQ      80(AX), BX
	VMOVDQA64 Y8, (BX)
	MOVQ      80(CX), BX
	VMOVDQU64 Y8, (BX)

noHash10:
	TESTL      $0x08000000, DX
	JZ         noHash11
	VSHUFI32X4 $0xee, Z8, Z8, Z8
	MOVQ       88(AX), BX
	VMOVDQA64  Y8, (BX)
	MOVQ       88(CX), BX
	VMOVDQU64  Y8, (BX)

noHash11:
	TESTL     $0x10000000, DX
	JZ        noHash12
	MOVQ      96(AX), BX
	VMOVDQA64 Y7, (BX)
	MOVQ      96(CX), BX
	VMOVDQU64 Y7, (BX)

noHash12:
	TESTL      $0x20000000, DX
	JZ         noHash13
	VSHUFI32X4 $0xee, Z7, Z7, Z7
	MOVQ       104(AX), BX
	VMOVDQA64  Y7, (BX)
	MOVQ       104(CX), BX
	VMOVDQU64  Y7, (BX)

noHash13:
	TESTL     $0x40000000, DX
	JZ        noHash14
	MOVQ      112(AX), BX
	VMOVDQA64 Y1, (BX)
	MOVQ      112(CX), BX
	VMOVDQU64 Y1, (BX)

noHash14:
	TESTL      $0x80000000, DX
	JZ         noHash15
	VSHUFI32X4 $0xee, Z1, Z1, Z1
	MOVQ       120(AX), BX
	VMOVDQA64  Y1, (BX)
	MOVQ       120(CX), BX
	VMOVDQU64  Y1, (BX)

noHash15:
	RET

// func Blake3AndCopy2048(blocks **byte, copy **byte, hash1 **byte, hash2 **byte, mask uint32)
// Requires: AVX512F, AVX512VL
TEXT ·Blake3AndCopy2048(SB), NOSPLIT, $0-36
	MOVQ         blocks+0(FP), AX
	MOVQ         copy+8(FP), CX
	MOVL         mask+32(FP), BX
	XORQ         DX, DX
	MOVD         $0x6a09e667, SI
	VPBROADCASTD SI, Z0
	MOVD         $0xbb67ae85, SI
	VPBROADCASTD SI, Z1
	MOVD         $0x3c6ef372, SI
	VPBROADCASTD SI, Z2
	MOVD         $0xa54ff53a, SI
	VPBROADCASTD SI, Z3
	MOVD         $0x510e527f, SI
	VPBROADCASTD SI, Z4
	MOVD         $0x9b05688c, SI
	VPBROADCASTD SI, Z5
	MOVD         $0x1f83d9ab, SI
	VPBROADCASTD SI, Z6
	MOVD         $0x5be0cd19, SI
	VPBROADCASTD SI, Z7
	MOVD         $0x6a09e667, SI
	MOVD         $0xbb67ae85, DI
	MOVD         $0x3c6ef372, R8
	MOVD         $0xa54ff53a, R9
	MOVD         $0x00000000, R10
	MOVD         $0x00000000, R11
	MOVD         $0x00000040, R12
	MOVD         $0x00000000, R13

loopStart:
	VPBROADCASTD BX, Z8
	TESTL        $0x00010000, BX
	JZ           copyEnd0
	MOVQ         (AX), R14
	VMOVDQA64    (R14), Z8
	TESTL        $0x00000001, BX
	JZ           copyEnd0
	MOVQ         (CX), R14
	ADDQ         DX, R14
	VMOVDQA64    Z8, (R14)

copyEnd0:
	VPBROADCASTD BX, Z9
	TESTL        $0x00020000, BX
	JZ           copyEnd1
	MOVQ         8(AX), R14
	VMOVDQA64    (R14), Z9
	TESTL        $0x00000002, BX
	JZ           copyEnd1
	MOVQ         8(CX), R14
	ADDQ         DX, R14
	VMOVDQA64    Z9, (R14)

copyEnd1:
	VPBROADCASTD BX, Z10
	TESTL        $0x00040000, BX
	JZ           copyEnd2
	MOVQ         16(AX), R14
	VMOVDQA64    (R14), Z10
	TESTL        $0x00000004, BX
	JZ           copyEnd2
	MOVQ         16(CX), R14
	ADDQ         DX, R14
	VMOVDQA64    Z10, (R14)

copyEnd2:
	VPBROADCASTD BX, Z11
	TESTL        $0x00080000, BX
	JZ           copyEnd3
	MOVQ         24(AX), R14
	VMOVDQA64    (R14), Z11
	TESTL        $0x00000008, BX
	JZ           copyEnd3
	MOVQ         24(CX), R14
	ADDQ         DX, R14
	VMOVDQA64    Z11, (R14)

copyEnd3:
	VPBROADCASTD BX, Z12
	TESTL        $0x00100000, BX
	JZ           copyEnd4
	MOVQ         32(AX), R14
	VMOVDQA64    (R14), Z12
	TESTL        $0x00000010, BX
	JZ           copyEnd4
	MOVQ         32(CX), R14
	ADDQ         DX, R14
	VMOVDQA64    Z12, (R14)

copyEnd4:
	VPBROADCASTD BX, Z13
	TESTL        $0x00200000, BX
	JZ           copyEnd5
	MOVQ         40(AX), R14
	VMOVDQA64    (R14), Z13
	TESTL        $0x00000020, BX
	JZ           copyEnd5
	MOVQ         40(CX), R14
	ADDQ         DX, R14
	VMOVDQA64    Z13, (R14)

copyEnd5:
	VPBROADCASTD BX, Z14
	TESTL        $0x00400000, BX
	JZ           copyEnd6
	MOVQ         48(AX), R14
	VMOVDQA64    (R14), Z14
	TESTL        $0x00000040, BX
	JZ           copyEnd6
	MOVQ         48(CX), R14
	ADDQ         DX, R14
	VMOVDQA64    Z14, (R14)

copyEnd6:
	VPBROADCASTD BX, Z15
	TESTL        $0x00800000, BX
	JZ           copyEnd7
	MOVQ         56(AX), R14
	VMOVDQA64    (R14), Z15
	TESTL        $0x00000080, BX
	JZ           copyEnd7
	MOVQ         56(CX), R14
	ADDQ         DX, R14
	VMOVDQA64    Z15, (R14)

copyEnd7:
	VPBROADCASTD BX, Z16
	TESTL        $0x01000000, BX
	JZ           copyEnd8
	MOVQ         64(AX), R14
	VMOVDQA64    (R14), Z16
	TESTL        $0x00000100, BX
	JZ           copyEnd8
	MOVQ         64(CX), R14
	ADDQ         DX, R14
	VMOVDQA64    Z16, (R14)

copyEnd8:
	VPBROADCASTD BX, Z17
	TESTL        $0x02000000, BX
	JZ           copyEnd9
	MOVQ         72(AX), R14
	VMOVDQA64    (R14), Z17
	TESTL        $0x00000200, BX
	JZ           copyEnd9
	MOVQ         72(CX), R14
	ADDQ         DX, R14
	VMOVDQA64    Z17, (R14)

copyEnd9:
	VPBROADCASTD BX, Z18
	TESTL        $0x04000000, BX
	JZ           copyEnd10
	MOVQ         80(AX), R14
	VMOVDQA64    (R14), Z18
	TESTL        $0x00000400, BX
	JZ           copyEnd10
	MOVQ         80(CX), R14
	ADDQ         DX, R14
	VMOVDQA64    Z18, (R14)

copyEnd10:
	VPBROADCASTD BX, Z19
	TESTL        $0x08000000, BX
	JZ           copyEnd11
	MOVQ         88(AX), R14
	VMOVDQA64    (R14), Z19
	TESTL        $0x00000800, BX
	JZ           copyEnd11
	MOVQ         88(CX), R14
	ADDQ         DX, R14
	VMOVDQA64    Z19, (R14)

copyEnd11:
	VPBROADCASTD BX, Z20
	TESTL        $0x10000000, BX
	JZ           copyEnd12
	MOVQ         96(AX), R14
	VMOVDQA64    (R14), Z20
	TESTL        $0x00001000, BX
	JZ           copyEnd12
	MOVQ         96(CX), R14
	ADDQ         DX, R14
	VMOVDQA64    Z20, (R14)

copyEnd12:
	VPBROADCASTD BX, Z21
	TESTL        $0x20000000, BX
	JZ           copyEnd13
	MOVQ         104(AX), R14
	VMOVDQA64    (R14), Z21
	TESTL        $0x00002000, BX
	JZ           copyEnd13
	MOVQ         104(CX), R14
	ADDQ         DX, R14
	VMOVDQA64    Z21, (R14)

copyEnd13:
	VPBROADCASTD BX, Z22
	TESTL        $0x40000000, BX
	JZ           copyEnd14
	MOVQ         112(AX), R14
	VMOVDQA64    (R14), Z22
	TESTL        $0x00004000, BX
	JZ           copyEnd14
	MOVQ         112(CX), R14
	ADDQ         DX, R14
	VMOVDQA64    Z22, (R14)

copyEnd14:
	VPBROADCASTD BX, Z23
	TESTL        $0x80000000, BX
	JZ           copyEnd15
	MOVQ         120(AX), R14
	VMOVDQA64    (R14), Z23
	TESTL        $0x00008000, BX
	JZ           copyEnd15
	MOVQ         120(CX), R14
	ADDQ         DX, R14
	VMOVDQA64    Z23, (R14)

copyEnd15:
	ADDQ         $0x40, DX
	VSHUFPS      $0x44, Z9, Z8, Z24
	VSHUFPS      $0xee, Z9, Z8, Z8
	VSHUFPS      $0x44, Z11, Z10, Z9
	VSHUFPS      $0xee, Z11, Z10, Z10
	VSHUFPS      $0x44, Z13, Z12, Z11
	VSHUFPS      $0xee, Z13, Z12, Z12
	VSHUFPS      $0x44, Z15, Z14, Z13
	VSHUFPS      $0xee, Z15, Z14, Z14
	VSHUFPS      $0x44, Z17, Z16, Z15
	VSHUFPS      $0xee, Z17, Z16, Z16
	VSHUFPS      $0x44, Z19, Z18, Z17
	VSHUFPS      $0xee, Z19, Z18, Z18
	VSHUFPS      $0x44, Z21, Z20, Z19
	VSHUFPS      $0xee, Z21, Z20, Z20
	VSHUFPS      $0x44, Z23, Z22, Z21
	VSHUFPS      $0xee, Z23, Z22, Z22
	VSHUFPS      $0x88, Z9, Z24, Z23
	VSHUFPS      $0xdd, Z9, Z24, Z24
	VSHUFPS      $0x88, Z10, Z8, Z9
	VSHUFPS      $0xdd, Z10, Z8, Z8
	VSHUFPS      $0x88, Z13, Z11, Z10
	VSHUFPS      $0xdd, Z13, Z11, Z11
	VSHUFPS      $0x88, Z14, Z12, Z13
	VSHUFPS      $0xdd, Z14, Z12, Z12
	VSHUFPS      $0x88, Z17, Z15, Z14
	VSHUFPS      $0xdd, Z17, Z15, Z15
	VSHUFPS      $0x88, Z18, Z16, Z17
	VSHUFPS      $0xdd, Z18, Z16, Z16
	VSHUFPS      $0x88, Z21, Z19, Z18
	VSHUFPS      $0xdd, Z21, Z19, Z19
	VSHUFPS      $0x88, Z22, Z20, Z21
	VSHUFPS      $0xdd, Z22, Z20, Z20
	VSHUFI32X4   $0x44, Z10, Z23, Z22
	VSHUFI32X4   $0xee, Z10, Z23, Z23
	VSHUFI32X4   $0x44, Z11, Z24, Z10
	VSHUFI32X4   $0xee, Z11, Z24, Z24
	VSHUFI32X4   $0x44, Z13, Z9, Z11
	VSHUFI32X4   $0xee, Z13, Z9, Z9
	VSHUFI32X4   $0x44, Z12, Z8, Z13
	VSHUFI32X4   $0xee, Z12, Z8, Z8
	VSHUFI32X4   $0x44, Z18, Z14, Z12
	VSHUFI32X4   $0xee, Z18, Z14, Z14
	VSHUFI32X4   $0x44, Z19, Z15, Z18
	VSHUFI32X4   $0xee, Z19, Z15, Z15
	VSHUFI32X4   $0x44, Z21, Z17, Z19
	VSHUFI32X4   $0xee, Z21, Z17, Z17
	VSHUFI32X4   $0x44, Z20, Z16, Z21
	VSHUFI32X4   $0xee, Z20, Z16, Z16
	VSHUFI32X4   $0x88, Z12, Z22, Z20
	VSHUFI32X4   $0xdd, Z12, Z22, Z22
	VSHUFI32X4   $0x88, Z18, Z10, Z12
	VSHUFI32X4   $0xdd, Z18, Z10, Z10
	VSHUFI32X4   $0x88, Z19, Z11, Z18
	VSHUFI32X4   $0xdd, Z19, Z11, Z11
	VSHUFI32X4   $0x88, Z21, Z13, Z19
	VSHUFI32X4   $0xdd, Z21, Z13, Z13
	VSHUFI32X4   $0x88, Z14, Z23, Z21
	VSHUFI32X4   $0xdd, Z14, Z23, Z23
	VSHUFI32X4   $0x88, Z15, Z24, Z14
	VSHUFI32X4   $0xdd, Z15, Z24, Z24
	VSHUFI32X4   $0x88, Z17, Z9, Z15
	VSHUFI32X4   $0xdd, Z17, Z9, Z9
	VSHUFI32X4   $0x88, Z16, Z8, Z17
	VSHUFI32X4   $0xdd, Z16, Z8, Z8
	VPBROADCASTD SI, Z16
	VPBROADCASTD DI, Z25
	VPBROADCASTD R8, Z26
	VPBROADCASTD R9, Z27
	VPBROADCASTD R10, Z28
	VPBROADCASTD R11, Z29
	VPBROADCASTD R12, Z30
	VPBROADCASTD R13, Z31
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z20, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z12, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z18, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z19, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z22, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z10, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z11, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z13, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z21, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z14, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z15, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z17, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z23, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z24, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z9, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z8, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z18, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z11, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z19, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z15, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z13, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z20, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z22, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z24, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z12, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z17, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z23, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z10, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z14, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z9, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z8, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z21, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z19, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z22, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z15, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z23, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z24, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z18, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z13, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z9, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z11, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z10, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z14, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z20, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z17, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z8, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z21, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z12, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z15, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z13, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z23, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z14, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z9, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z19, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z24, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z8, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z22, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z20, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z17, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z18, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z10, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z21, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z12, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z11, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z23, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z24, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z14, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z17, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z8, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z15, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z9, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z21, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z13, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z18, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z10, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z19, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z20, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z12, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z11, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z22, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z14, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z9, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z17, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z10, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z21, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z23, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z8, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z12, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z24, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z19, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z20, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z15, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z18, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z11, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z22, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z13, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z17, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z8, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z10, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z20, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z12, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z14, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z21, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z11, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z9, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z15, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z18, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z23, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z19, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z22, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z13, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z24, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x07, Z4, Z4
	VPXORD       Z0, Z16, Z0
	VPXORD       Z1, Z25, Z1
	VPXORD       Z2, Z26, Z2
	VPXORD       Z3, Z27, Z3
	VPXORD       Z4, Z28, Z4
	VPXORD       Z5, Z29, Z5
	VPXORD       Z6, Z30, Z6
	VPXORD       Z7, Z31, Z7
	CMPQ         DX, $0x00000800
	JNE          loopStart
	VSHUFPS      $0x44, Z1, Z0, Z8
	VSHUFPS      $0xee, Z1, Z0, Z0
	VSHUFPS      $0x44, Z3, Z2, Z1
	VSHUFPS      $0xee, Z3, Z2, Z2
	VSHUFPS      $0x44, Z5, Z4, Z3
	VSHUFPS      $0xee, Z5, Z4, Z4
	VSHUFPS      $0x44, Z7, Z6, Z5
	VSHUFPS      $0xee, Z7, Z6, Z6
	VSHUFPS      $0x88, Z1, Z8, Z7
	VSHUFPS      $0xdd, Z1, Z8, Z8
	VSHUFPS      $0x88, Z2, Z0, Z1
	VSHUFPS      $0xdd, Z2, Z0, Z0
	VSHUFPS      $0x88, Z5, Z3, Z2
	VSHUFPS      $0xdd, Z5, Z3, Z3
	VSHUFPS      $0x88, Z6, Z4, Z5
	VSHUFPS      $0xdd, Z6, Z4, Z4
	VSHUFI32X4   $0x44, Z2, Z7, Z6
	VSHUFI32X4   $0xee, Z2, Z7, Z7
	VSHUFI32X4   $0x44, Z3, Z8, Z2
	VSHUFI32X4   $0xee, Z3, Z8, Z8
	VSHUFI32X4   $0x44, Z5, Z1, Z3
	VSHUFI32X4   $0xee, Z5, Z1, Z1
	VSHUFI32X4   $0x44, Z4, Z0, Z5
	VSHUFI32X4   $0xee, Z4, Z0, Z0
	VSHUFI32X4   $0x88, Z2, Z6, Z4
	VSHUFI32X4   $0xdd, Z2, Z6, Z6
	VSHUFI32X4   $0x88, Z5, Z3, Z2
	VSHUFI32X4   $0xdd, Z5, Z3, Z3
	VSHUFI32X4   $0x88, Z8, Z7, Z5
	VSHUFI32X4   $0xdd, Z8, Z7, Z7
	VSHUFI32X4   $0x88, Z0, Z1, Z8
	VSHUFI32X4   $0xdd, Z0, Z1, Z1
	MOVQ         hash1+16(FP), SI
	MOVQ         hash2+24(FP), DI
	TESTL        $0x00010000, BX
	JZ           noHash0
	MOVQ         (SI), R8
	VMOVDQA64    Y4, (R8)
	MOVQ         (DI), R8
	VMOVDQU64    Y4, (R8)

noHash0:
	TESTL      $0x00020000, BX
	JZ         noHash1
	VSHUFI32X4 $0xee, Z4, Z4, Z4
	MOVQ       8(SI), R8
	VMOVDQA64  Y4, (R8)
	MOVQ       8(DI), R8
	VMOVDQU64  Y4, (R8)

noHash1:
	TESTL     $0x00040000, BX
	JZ        noHash2
	MOVQ      16(SI), R8
	VMOVDQA64 Y2, (R8)
	MOVQ      16(DI), R8
	VMOVDQU64 Y2, (R8)

noHash2:
	TESTL      $0x00080000, BX
	JZ         noHash3
	VSHUFI32X4 $0xee, Z2, Z2, Z2
	MOVQ       24(SI), R8
	VMOVDQA64  Y2, (R8)
	MOVQ       24(DI), R8
	VMOVDQU64  Y2, (R8)

noHash3:
	TESTL     $0x00100000, BX
	JZ        noHash4
	MOVQ      32(SI), R8
	VMOVDQA64 Y6, (R8)
	MOVQ      32(DI), R8
	VMOVDQU64 Y6, (R8)

noHash4:
	TESTL      $0x00200000, BX
	JZ         noHash5
	VSHUFI32X4 $0xee, Z6, Z6, Z6
	MOVQ       40(SI), R8
	VMOVDQA64  Y6, (R8)
	MOVQ       40(DI), R8
	VMOVDQU64  Y6, (R8)

noHash5:
	TESTL     $0x00400000, BX
	JZ        noHash6
	MOVQ      48(SI), R8
	VMOVDQA64 Y3, (R8)
	MOVQ      48(DI), R8
	VMOVDQU64 Y3, (R8)

noHash6:
	TESTL      $0x00800000, BX
	JZ         noHash7
	VSHUFI32X4 $0xee, Z3, Z3, Z3
	MOVQ       56(SI), R8
	VMOVDQA64  Y3, (R8)
	MOVQ       56(DI), R8
	VMOVDQU64  Y3, (R8)

noHash7:
	TESTL     $0x01000000, BX
	JZ        noHash8
	MOVQ      64(SI), R8
	VMOVDQA64 Y5, (R8)
	MOVQ      64(DI), R8
	VMOVDQU64 Y5, (R8)

noHash8:
	TESTL      $0x02000000, BX
	JZ         noHash9
	VSHUFI32X4 $0xee, Z5, Z5, Z5
	MOVQ       72(SI), R8
	VMOVDQA64  Y5, (R8)
	MOVQ       72(DI), R8
	VMOVDQU64  Y5, (R8)

noHash9:
	TESTL     $0x04000000, BX
	JZ        noHash10
	MOVQ      80(SI), R8
	VMOVDQA64 Y8, (R8)
	MOVQ      80(DI), R8
	VMOVDQU64 Y8, (R8)

noHash10:
	TESTL      $0x08000000, BX
	JZ         noHash11
	VSHUFI32X4 $0xee, Z8, Z8, Z8
	MOVQ       88(SI), R8
	VMOVDQA64  Y8, (R8)
	MOVQ       88(DI), R8
	VMOVDQU64  Y8, (R8)

noHash11:
	TESTL     $0x10000000, BX
	JZ        noHash12
	MOVQ      96(SI), R8
	VMOVDQA64 Y7, (R8)
	MOVQ      96(DI), R8
	VMOVDQU64 Y7, (R8)

noHash12:
	TESTL      $0x20000000, BX
	JZ         noHash13
	VSHUFI32X4 $0xee, Z7, Z7, Z7
	MOVQ       104(SI), R8
	VMOVDQA64  Y7, (R8)
	MOVQ       104(DI), R8
	VMOVDQU64  Y7, (R8)

noHash13:
	TESTL     $0x40000000, BX
	JZ        noHash14
	MOVQ      112(SI), R8
	VMOVDQA64 Y1, (R8)
	MOVQ      112(DI), R8
	VMOVDQU64 Y1, (R8)

noHash14:
	TESTL      $0x80000000, BX
	JZ         noHash15
	VSHUFI32X4 $0xee, Z1, Z1, Z1
	MOVQ       120(SI), R8
	VMOVDQA64  Y1, (R8)
	MOVQ       120(DI), R8
	VMOVDQU64  Y1, (R8)

noHash15:
	TESTL $0x00000001, BX
	JZ    copyEnd20
	MOVQ  (CX), SI
	MOVQ  (AX), DI
	MOVQ  DX, R8
	ADDQ  R8, DI
	ADDQ  R8, SI

loopCopyStart0:
	VMOVDQA64 (DI), Z0
	VMOVDQA64 Z0, (SI)
	ADDQ      $0x40, DI
	ADDQ      $0x40, SI
	ADDQ      $0x40, R8
	CMPQ      R8, $0x00001000
	JNE       loopCopyStart0

copyEnd20:
	TESTL $0x00000002, BX
	JZ    copyEnd21
	MOVQ  8(CX), SI
	MOVQ  8(AX), DI
	MOVQ  DX, R8
	ADDQ  R8, DI
	ADDQ  R8, SI

loopCopyStart1:
	VMOVDQA64 (DI), Z0
	VMOVDQA64 Z0, (SI)
	ADDQ      $0x40, DI
	ADDQ      $0x40, SI
	ADDQ      $0x40, R8
	CMPQ      R8, $0x00001000
	JNE       loopCopyStart1

copyEnd21:
	TESTL $0x00000004, BX
	JZ    copyEnd22
	MOVQ  16(CX), SI
	MOVQ  16(AX), DI
	MOVQ  DX, R8
	ADDQ  R8, DI
	ADDQ  R8, SI

loopCopyStart2:
	VMOVDQA64 (DI), Z0
	VMOVDQA64 Z0, (SI)
	ADDQ      $0x40, DI
	ADDQ      $0x40, SI
	ADDQ      $0x40, R8
	CMPQ      R8, $0x00001000
	JNE       loopCopyStart2

copyEnd22:
	TESTL $0x00000008, BX
	JZ    copyEnd23
	MOVQ  24(CX), SI
	MOVQ  24(AX), DI
	MOVQ  DX, R8
	ADDQ  R8, DI
	ADDQ  R8, SI

loopCopyStart3:
	VMOVDQA64 (DI), Z0
	VMOVDQA64 Z0, (SI)
	ADDQ      $0x40, DI
	ADDQ      $0x40, SI
	ADDQ      $0x40, R8
	CMPQ      R8, $0x00001000
	JNE       loopCopyStart3

copyEnd23:
	TESTL $0x00000010, BX
	JZ    copyEnd24
	MOVQ  32(CX), SI
	MOVQ  32(AX), DI
	MOVQ  DX, R8
	ADDQ  R8, DI
	ADDQ  R8, SI

loopCopyStart4:
	VMOVDQA64 (DI), Z0
	VMOVDQA64 Z0, (SI)
	ADDQ      $0x40, DI
	ADDQ      $0x40, SI
	ADDQ      $0x40, R8
	CMPQ      R8, $0x00001000
	JNE       loopCopyStart4

copyEnd24:
	TESTL $0x00000020, BX
	JZ    copyEnd25
	MOVQ  40(CX), SI
	MOVQ  40(AX), DI
	MOVQ  DX, R8
	ADDQ  R8, DI
	ADDQ  R8, SI

loopCopyStart5:
	VMOVDQA64 (DI), Z0
	VMOVDQA64 Z0, (SI)
	ADDQ      $0x40, DI
	ADDQ      $0x40, SI
	ADDQ      $0x40, R8
	CMPQ      R8, $0x00001000
	JNE       loopCopyStart5

copyEnd25:
	TESTL $0x00000040, BX
	JZ    copyEnd26
	MOVQ  48(CX), SI
	MOVQ  48(AX), DI
	MOVQ  DX, R8
	ADDQ  R8, DI
	ADDQ  R8, SI

loopCopyStart6:
	VMOVDQA64 (DI), Z0
	VMOVDQA64 Z0, (SI)
	ADDQ      $0x40, DI
	ADDQ      $0x40, SI
	ADDQ      $0x40, R8
	CMPQ      R8, $0x00001000
	JNE       loopCopyStart6

copyEnd26:
	TESTL $0x00000080, BX
	JZ    copyEnd27
	MOVQ  56(CX), SI
	MOVQ  56(AX), DI
	MOVQ  DX, R8
	ADDQ  R8, DI
	ADDQ  R8, SI

loopCopyStart7:
	VMOVDQA64 (DI), Z0
	VMOVDQA64 Z0, (SI)
	ADDQ      $0x40, DI
	ADDQ      $0x40, SI
	ADDQ      $0x40, R8
	CMPQ      R8, $0x00001000
	JNE       loopCopyStart7

copyEnd27:
	TESTL $0x00000100, BX
	JZ    copyEnd28
	MOVQ  64(CX), SI
	MOVQ  64(AX), DI
	MOVQ  DX, R8
	ADDQ  R8, DI
	ADDQ  R8, SI

loopCopyStart8:
	VMOVDQA64 (DI), Z0
	VMOVDQA64 Z0, (SI)
	ADDQ      $0x40, DI
	ADDQ      $0x40, SI
	ADDQ      $0x40, R8
	CMPQ      R8, $0x00001000
	JNE       loopCopyStart8

copyEnd28:
	TESTL $0x00000200, BX
	JZ    copyEnd29
	MOVQ  72(CX), SI
	MOVQ  72(AX), DI
	MOVQ  DX, R8
	ADDQ  R8, DI
	ADDQ  R8, SI

loopCopyStart9:
	VMOVDQA64 (DI), Z0
	VMOVDQA64 Z0, (SI)
	ADDQ      $0x40, DI
	ADDQ      $0x40, SI
	ADDQ      $0x40, R8
	CMPQ      R8, $0x00001000
	JNE       loopCopyStart9

copyEnd29:
	TESTL $0x00000400, BX
	JZ    copyEnd210
	MOVQ  80(CX), SI
	MOVQ  80(AX), DI
	MOVQ  DX, R8
	ADDQ  R8, DI
	ADDQ  R8, SI

loopCopyStart10:
	VMOVDQA64 (DI), Z0
	VMOVDQA64 Z0, (SI)
	ADDQ      $0x40, DI
	ADDQ      $0x40, SI
	ADDQ      $0x40, R8
	CMPQ      R8, $0x00001000
	JNE       loopCopyStart10

copyEnd210:
	TESTL $0x00000800, BX
	JZ    copyEnd211
	MOVQ  88(CX), SI
	MOVQ  88(AX), DI
	MOVQ  DX, R8
	ADDQ  R8, DI
	ADDQ  R8, SI

loopCopyStart11:
	VMOVDQA64 (DI), Z0
	VMOVDQA64 Z0, (SI)
	ADDQ      $0x40, DI
	ADDQ      $0x40, SI
	ADDQ      $0x40, R8
	CMPQ      R8, $0x00001000
	JNE       loopCopyStart11

copyEnd211:
	TESTL $0x00001000, BX
	JZ    copyEnd212
	MOVQ  96(CX), SI
	MOVQ  96(AX), DI
	MOVQ  DX, R8
	ADDQ  R8, DI
	ADDQ  R8, SI

loopCopyStart12:
	VMOVDQA64 (DI), Z0
	VMOVDQA64 Z0, (SI)
	ADDQ      $0x40, DI
	ADDQ      $0x40, SI
	ADDQ      $0x40, R8
	CMPQ      R8, $0x00001000
	JNE       loopCopyStart12

copyEnd212:
	TESTL $0x00002000, BX
	JZ    copyEnd213
	MOVQ  104(CX), SI
	MOVQ  104(AX), DI
	MOVQ  DX, R8
	ADDQ  R8, DI
	ADDQ  R8, SI

loopCopyStart13:
	VMOVDQA64 (DI), Z0
	VMOVDQA64 Z0, (SI)
	ADDQ      $0x40, DI
	ADDQ      $0x40, SI
	ADDQ      $0x40, R8
	CMPQ      R8, $0x00001000
	JNE       loopCopyStart13

copyEnd213:
	TESTL $0x00004000, BX
	JZ    copyEnd214
	MOVQ  112(CX), SI
	MOVQ  112(AX), DI
	MOVQ  DX, R8
	ADDQ  R8, DI
	ADDQ  R8, SI

loopCopyStart14:
	VMOVDQA64 (DI), Z0
	VMOVDQA64 Z0, (SI)
	ADDQ      $0x40, DI
	ADDQ      $0x40, SI
	ADDQ      $0x40, R8
	CMPQ      R8, $0x00001000
	JNE       loopCopyStart14

copyEnd214:
	TESTL $0x00008000, BX
	JZ    copyEnd215
	MOVQ  120(CX), CX
	MOVQ  120(AX), AX
	ADDQ  DX, AX
	ADDQ  DX, CX

loopCopyStart15:
	VMOVDQA64 (AX), Z0
	VMOVDQA64 Z0, (CX)
	ADDQ      $0x40, AX
	ADDQ      $0x40, CX
	ADDQ      $0x40, DX
	CMPQ      DX, $0x00001000
	JNE       loopCopyStart15

copyEnd215:
	RET
