// Code generated by command: go run avo.go -out ../asm.s -stubs ../asm_stub.go -pkg hash. DO NOT EDIT.

#include "textflag.h"

// func Blake3AndCopy4096(blocks **byte, copy **byte, hash1 **byte, hash2 **byte, copyMask uint16)
// Requires: AVX512F, AVX512VL
TEXT ·Blake3AndCopy4096(SB), NOSPLIT, $0-34
	MOVQ         blocks+0(FP), AX
	MOVQ         copy+8(FP), CX
	MOVW         copyMask+32(FP), DX
	XORQ         BX, BX
	MOVD         $0x6a09e667, SI
	VPBROADCASTD SI, Z0
	MOVD         $0xbb67ae85, SI
	VPBROADCASTD SI, Z1
	MOVD         $0x3c6ef372, SI
	VPBROADCASTD SI, Z2
	MOVD         $0xa54ff53a, SI
	VPBROADCASTD SI, Z3
	MOVD         $0x510e527f, SI
	VPBROADCASTD SI, Z4
	MOVD         $0x9b05688c, SI
	VPBROADCASTD SI, Z5
	MOVD         $0x1f83d9ab, SI
	VPBROADCASTD SI, Z6
	MOVD         $0x5be0cd19, SI
	VPBROADCASTD SI, Z7
	MOVD         $0x6a09e667, SI
	MOVD         $0xbb67ae85, DI
	MOVD         $0x3c6ef372, R8
	MOVD         $0xa54ff53a, R9
	MOVD         $0x00000000, R10
	MOVD         $0x00000000, R11
	MOVD         $0x00000040, R12
	MOVD         $0x00000000, R13

loopStart:
	MOVQ      (AX), R14
	ADDQ      BX, R14
	VMOVDQA64 (R14), Z8
	TESTW     $0x0001, DX
	JZ        copyEnd0
	MOVQ      (CX), R14
	ADDQ      BX, R14
	VMOVDQA64 Z8, (R14)

copyEnd0:
	MOVQ      8(AX), R14
	ADDQ      BX, R14
	VMOVDQA64 (R14), Z9
	TESTW     $0x0002, DX
	JZ        copyEnd1
	MOVQ      8(CX), R14
	ADDQ      BX, R14
	VMOVDQA64 Z9, (R14)

copyEnd1:
	MOVQ      16(AX), R14
	ADDQ      BX, R14
	VMOVDQA64 (R14), Z10
	TESTW     $0x0004, DX
	JZ        copyEnd2
	MOVQ      16(CX), R14
	ADDQ      BX, R14
	VMOVDQA64 Z10, (R14)

copyEnd2:
	MOVQ      24(AX), R14
	ADDQ      BX, R14
	VMOVDQA64 (R14), Z11
	TESTW     $0x0008, DX
	JZ        copyEnd3
	MOVQ      24(CX), R14
	ADDQ      BX, R14
	VMOVDQA64 Z11, (R14)

copyEnd3:
	MOVQ      32(AX), R14
	ADDQ      BX, R14
	VMOVDQA64 (R14), Z12
	TESTW     $0x0010, DX
	JZ        copyEnd4
	MOVQ      32(CX), R14
	ADDQ      BX, R14
	VMOVDQA64 Z12, (R14)

copyEnd4:
	MOVQ      40(AX), R14
	ADDQ      BX, R14
	VMOVDQA64 (R14), Z13
	TESTW     $0x0020, DX
	JZ        copyEnd5
	MOVQ      40(CX), R14
	ADDQ      BX, R14
	VMOVDQA64 Z13, (R14)

copyEnd5:
	MOVQ      48(AX), R14
	ADDQ      BX, R14
	VMOVDQA64 (R14), Z14
	TESTW     $0x0040, DX
	JZ        copyEnd6
	MOVQ      48(CX), R14
	ADDQ      BX, R14
	VMOVDQA64 Z14, (R14)

copyEnd6:
	MOVQ      56(AX), R14
	ADDQ      BX, R14
	VMOVDQA64 (R14), Z15
	TESTW     $0x0080, DX
	JZ        copyEnd7
	MOVQ      56(CX), R14
	ADDQ      BX, R14
	VMOVDQA64 Z15, (R14)

copyEnd7:
	MOVQ      64(AX), R14
	ADDQ      BX, R14
	VMOVDQA64 (R14), Z16
	TESTW     $0x0100, DX
	JZ        copyEnd8
	MOVQ      64(CX), R14
	ADDQ      BX, R14
	VMOVDQA64 Z16, (R14)

copyEnd8:
	MOVQ      72(AX), R14
	ADDQ      BX, R14
	VMOVDQA64 (R14), Z17
	TESTW     $0x0200, DX
	JZ        copyEnd9
	MOVQ      72(CX), R14
	ADDQ      BX, R14
	VMOVDQA64 Z17, (R14)

copyEnd9:
	MOVQ      80(AX), R14
	ADDQ      BX, R14
	VMOVDQA64 (R14), Z18
	TESTW     $0x0400, DX
	JZ        copyEnd10
	MOVQ      80(CX), R14
	ADDQ      BX, R14
	VMOVDQA64 Z18, (R14)

copyEnd10:
	MOVQ      88(AX), R14
	ADDQ      BX, R14
	VMOVDQA64 (R14), Z19
	TESTW     $0x0800, DX
	JZ        copyEnd11
	MOVQ      88(CX), R14
	ADDQ      BX, R14
	VMOVDQA64 Z19, (R14)

copyEnd11:
	MOVQ      96(AX), R14
	ADDQ      BX, R14
	VMOVDQA64 (R14), Z20
	TESTW     $0x1000, DX
	JZ        copyEnd12
	MOVQ      96(CX), R14
	ADDQ      BX, R14
	VMOVDQA64 Z20, (R14)

copyEnd12:
	MOVQ      104(AX), R14
	ADDQ      BX, R14
	VMOVDQA64 (R14), Z21
	TESTW     $0x2000, DX
	JZ        copyEnd13
	MOVQ      104(CX), R14
	ADDQ      BX, R14
	VMOVDQA64 Z21, (R14)

copyEnd13:
	MOVQ      112(AX), R14
	ADDQ      BX, R14
	VMOVDQA64 (R14), Z22
	TESTW     $0x4000, DX
	JZ        copyEnd14
	MOVQ      112(CX), R14
	ADDQ      BX, R14
	VMOVDQA64 Z22, (R14)

copyEnd14:
	MOVQ      120(AX), R14
	ADDQ      BX, R14
	VMOVDQA64 (R14), Z23
	TESTW     $0x8000, DX
	JZ        copyEnd15
	MOVQ      120(CX), R14
	ADDQ      BX, R14
	VMOVDQA64 Z23, (R14)

copyEnd15:
	ADDQ         $0x40, BX
	VSHUFPS      $0x44, Z9, Z8, Z24
	VSHUFPS      $0xee, Z9, Z8, Z8
	VSHUFPS      $0x44, Z11, Z10, Z9
	VSHUFPS      $0xee, Z11, Z10, Z10
	VSHUFPS      $0x44, Z13, Z12, Z11
	VSHUFPS      $0xee, Z13, Z12, Z12
	VSHUFPS      $0x44, Z15, Z14, Z13
	VSHUFPS      $0xee, Z15, Z14, Z14
	VSHUFPS      $0x44, Z17, Z16, Z15
	VSHUFPS      $0xee, Z17, Z16, Z16
	VSHUFPS      $0x44, Z19, Z18, Z17
	VSHUFPS      $0xee, Z19, Z18, Z18
	VSHUFPS      $0x44, Z21, Z20, Z19
	VSHUFPS      $0xee, Z21, Z20, Z20
	VSHUFPS      $0x44, Z23, Z22, Z21
	VSHUFPS      $0xee, Z23, Z22, Z22
	VSHUFPS      $0x88, Z9, Z24, Z23
	VSHUFPS      $0xdd, Z9, Z24, Z24
	VSHUFPS      $0x88, Z10, Z8, Z9
	VSHUFPS      $0xdd, Z10, Z8, Z8
	VSHUFPS      $0x88, Z13, Z11, Z10
	VSHUFPS      $0xdd, Z13, Z11, Z11
	VSHUFPS      $0x88, Z14, Z12, Z13
	VSHUFPS      $0xdd, Z14, Z12, Z12
	VSHUFPS      $0x88, Z17, Z15, Z14
	VSHUFPS      $0xdd, Z17, Z15, Z15
	VSHUFPS      $0x88, Z18, Z16, Z17
	VSHUFPS      $0xdd, Z18, Z16, Z16
	VSHUFPS      $0x88, Z21, Z19, Z18
	VSHUFPS      $0xdd, Z21, Z19, Z19
	VSHUFPS      $0x88, Z22, Z20, Z21
	VSHUFPS      $0xdd, Z22, Z20, Z20
	VSHUFI32X4   $0x44, Z10, Z23, Z22
	VSHUFI32X4   $0xee, Z10, Z23, Z23
	VSHUFI32X4   $0x44, Z11, Z24, Z10
	VSHUFI32X4   $0xee, Z11, Z24, Z24
	VSHUFI32X4   $0x44, Z13, Z9, Z11
	VSHUFI32X4   $0xee, Z13, Z9, Z9
	VSHUFI32X4   $0x44, Z12, Z8, Z13
	VSHUFI32X4   $0xee, Z12, Z8, Z8
	VSHUFI32X4   $0x44, Z18, Z14, Z12
	VSHUFI32X4   $0xee, Z18, Z14, Z14
	VSHUFI32X4   $0x44, Z19, Z15, Z18
	VSHUFI32X4   $0xee, Z19, Z15, Z15
	VSHUFI32X4   $0x44, Z21, Z17, Z19
	VSHUFI32X4   $0xee, Z21, Z17, Z17
	VSHUFI32X4   $0x44, Z20, Z16, Z21
	VSHUFI32X4   $0xee, Z20, Z16, Z16
	VSHUFI32X4   $0x88, Z12, Z22, Z20
	VSHUFI32X4   $0xdd, Z12, Z22, Z22
	VSHUFI32X4   $0x88, Z18, Z10, Z12
	VSHUFI32X4   $0xdd, Z18, Z10, Z10
	VSHUFI32X4   $0x88, Z19, Z11, Z18
	VSHUFI32X4   $0xdd, Z19, Z11, Z11
	VSHUFI32X4   $0x88, Z21, Z13, Z19
	VSHUFI32X4   $0xdd, Z21, Z13, Z13
	VSHUFI32X4   $0x88, Z14, Z23, Z21
	VSHUFI32X4   $0xdd, Z14, Z23, Z23
	VSHUFI32X4   $0x88, Z15, Z24, Z14
	VSHUFI32X4   $0xdd, Z15, Z24, Z24
	VSHUFI32X4   $0x88, Z17, Z9, Z15
	VSHUFI32X4   $0xdd, Z17, Z9, Z9
	VSHUFI32X4   $0x88, Z16, Z8, Z17
	VSHUFI32X4   $0xdd, Z16, Z8, Z8
	VPBROADCASTD SI, Z16
	VPBROADCASTD DI, Z25
	VPBROADCASTD R8, Z26
	VPBROADCASTD R9, Z27
	VPBROADCASTD R10, Z28
	VPBROADCASTD R11, Z29
	VPBROADCASTD R12, Z30
	VPBROADCASTD R13, Z31
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z20, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z12, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z18, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z19, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z22, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z10, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z11, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z13, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z21, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z14, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z15, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z17, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z23, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z24, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z9, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z8, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z18, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z11, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z19, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z15, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z13, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z20, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z22, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z24, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z12, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z17, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z23, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z10, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z14, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z9, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z8, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z21, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z19, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z22, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z15, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z23, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z24, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z18, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z13, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z9, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z11, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z10, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z14, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z20, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z17, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z8, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z21, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z12, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z15, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z13, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z23, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z14, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z9, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z19, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z24, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z8, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z22, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z20, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z17, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z18, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z10, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z21, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z12, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z11, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z23, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z24, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z14, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z17, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z8, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z15, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z9, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z21, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z13, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z18, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z10, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z19, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z20, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z12, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z11, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z22, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z14, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z9, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z17, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z10, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z21, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z23, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z8, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z12, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z24, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z19, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z20, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z15, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z18, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z11, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z22, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z13, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z17, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z8, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z10, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z20, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z12, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z14, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z21, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z11, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z9, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z15, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z18, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z23, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z19, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z22, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z13, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z24, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x07, Z4, Z4
	VPXORD       Z0, Z16, Z0
	VPXORD       Z1, Z25, Z1
	VPXORD       Z2, Z26, Z2
	VPXORD       Z3, Z27, Z3
	VPXORD       Z4, Z28, Z4
	VPXORD       Z5, Z29, Z5
	VPXORD       Z6, Z30, Z6
	VPXORD       Z7, Z31, Z7
	CMPQ         BX, $0x00001000
	JNE          loopStart
	VSHUFPS      $0x44, Z1, Z0, Z8
	VSHUFPS      $0xee, Z1, Z0, Z0
	VSHUFPS      $0x44, Z3, Z2, Z1
	VSHUFPS      $0xee, Z3, Z2, Z2
	VSHUFPS      $0x44, Z5, Z4, Z3
	VSHUFPS      $0xee, Z5, Z4, Z4
	VSHUFPS      $0x44, Z7, Z6, Z5
	VSHUFPS      $0xee, Z7, Z6, Z6
	VSHUFPS      $0x88, Z1, Z8, Z7
	VSHUFPS      $0xdd, Z1, Z8, Z8
	VSHUFPS      $0x88, Z2, Z0, Z1
	VSHUFPS      $0xdd, Z2, Z0, Z0
	VSHUFPS      $0x88, Z5, Z3, Z2
	VSHUFPS      $0xdd, Z5, Z3, Z3
	VSHUFPS      $0x88, Z6, Z4, Z5
	VSHUFPS      $0xdd, Z6, Z4, Z4
	VSHUFI32X4   $0x44, Z2, Z7, Z6
	VSHUFI32X4   $0xee, Z2, Z7, Z7
	VSHUFI32X4   $0x44, Z3, Z8, Z2
	VSHUFI32X4   $0xee, Z3, Z8, Z8
	VSHUFI32X4   $0x44, Z5, Z1, Z3
	VSHUFI32X4   $0xee, Z5, Z1, Z1
	VSHUFI32X4   $0x44, Z4, Z0, Z5
	VSHUFI32X4   $0xee, Z4, Z0, Z0
	VSHUFI32X4   $0x88, Z2, Z6, Z4
	VSHUFI32X4   $0xdd, Z2, Z6, Z6
	VSHUFI32X4   $0x88, Z5, Z3, Z2
	VSHUFI32X4   $0xdd, Z5, Z3, Z3
	VSHUFI32X4   $0x88, Z8, Z7, Z5
	VSHUFI32X4   $0xdd, Z8, Z7, Z7
	VSHUFI32X4   $0x88, Z0, Z1, Z8
	VSHUFI32X4   $0xdd, Z0, Z1, Z1
	MOVQ         hash1+16(FP), AX
	MOVQ         hash2+24(FP), CX
	MOVQ         (AX), DX
	VMOVDQA64    Y4, (DX)
	MOVQ         (CX), DX
	VMOVDQU64    Y4, (DX)
	VSHUFI32X4   $0xee, Z4, Z4, Z4
	MOVQ         8(AX), DX
	VMOVDQA64    Y4, (DX)
	MOVQ         8(CX), DX
	VMOVDQU64    Y4, (DX)
	MOVQ         16(AX), DX
	VMOVDQA64    Y2, (DX)
	MOVQ         16(CX), DX
	VMOVDQU64    Y2, (DX)
	VSHUFI32X4   $0xee, Z2, Z2, Z2
	MOVQ         24(AX), DX
	VMOVDQA64    Y2, (DX)
	MOVQ         24(CX), DX
	VMOVDQU64    Y2, (DX)
	MOVQ         32(AX), DX
	VMOVDQA64    Y6, (DX)
	MOVQ         32(CX), DX
	VMOVDQU64    Y6, (DX)
	VSHUFI32X4   $0xee, Z6, Z6, Z6
	MOVQ         40(AX), DX
	VMOVDQA64    Y6, (DX)
	MOVQ         40(CX), DX
	VMOVDQU64    Y6, (DX)
	MOVQ         48(AX), DX
	VMOVDQA64    Y3, (DX)
	MOVQ         48(CX), DX
	VMOVDQU64    Y3, (DX)
	VSHUFI32X4   $0xee, Z3, Z3, Z3
	MOVQ         56(AX), DX
	VMOVDQA64    Y3, (DX)
	MOVQ         56(CX), DX
	VMOVDQU64    Y3, (DX)
	MOVQ         64(AX), DX
	VMOVDQA64    Y5, (DX)
	MOVQ         64(CX), DX
	VMOVDQU64    Y5, (DX)
	VSHUFI32X4   $0xee, Z5, Z5, Z5
	MOVQ         72(AX), DX
	VMOVDQA64    Y5, (DX)
	MOVQ         72(CX), DX
	VMOVDQU64    Y5, (DX)
	MOVQ         80(AX), DX
	VMOVDQA64    Y8, (DX)
	MOVQ         80(CX), DX
	VMOVDQU64    Y8, (DX)
	VSHUFI32X4   $0xee, Z8, Z8, Z8
	MOVQ         88(AX), DX
	VMOVDQA64    Y8, (DX)
	MOVQ         88(CX), DX
	VMOVDQU64    Y8, (DX)
	MOVQ         96(AX), DX
	VMOVDQA64    Y7, (DX)
	MOVQ         96(CX), DX
	VMOVDQU64    Y7, (DX)
	VSHUFI32X4   $0xee, Z7, Z7, Z7
	MOVQ         104(AX), DX
	VMOVDQA64    Y7, (DX)
	MOVQ         104(CX), DX
	VMOVDQU64    Y7, (DX)
	MOVQ         112(AX), DX
	VMOVDQA64    Y1, (DX)
	MOVQ         112(CX), DX
	VMOVDQU64    Y1, (DX)
	VSHUFI32X4   $0xee, Z1, Z1, Z1
	MOVQ         120(AX), DX
	VMOVDQA64    Y1, (DX)
	MOVQ         120(CX), DX
	VMOVDQU64    Y1, (DX)
	RET

// func Blake3AndCopy2048(blocks **byte, copy **byte, hash1 **byte, hash2 **byte, copyMask uint16)
// Requires: AVX512F, AVX512VL
TEXT ·Blake3AndCopy2048(SB), NOSPLIT, $0-34
	MOVQ         blocks+0(FP), AX
	MOVQ         copy+8(FP), CX
	MOVW         copyMask+32(FP), DX
	XORQ         BX, BX
	MOVD         $0x6a09e667, SI
	VPBROADCASTD SI, Z0
	MOVD         $0xbb67ae85, SI
	VPBROADCASTD SI, Z1
	MOVD         $0x3c6ef372, SI
	VPBROADCASTD SI, Z2
	MOVD         $0xa54ff53a, SI
	VPBROADCASTD SI, Z3
	MOVD         $0x510e527f, SI
	VPBROADCASTD SI, Z4
	MOVD         $0x9b05688c, SI
	VPBROADCASTD SI, Z5
	MOVD         $0x1f83d9ab, SI
	VPBROADCASTD SI, Z6
	MOVD         $0x5be0cd19, SI
	VPBROADCASTD SI, Z7
	MOVD         $0x6a09e667, SI
	MOVD         $0xbb67ae85, DI
	MOVD         $0x3c6ef372, R8
	MOVD         $0xa54ff53a, R9
	MOVD         $0x00000000, R10
	MOVD         $0x00000000, R11
	MOVD         $0x00000040, R12
	MOVD         $0x00000000, R13

loopStart:
	MOVQ      (AX), R14
	ADDQ      BX, R14
	VMOVDQA64 (R14), Z8
	TESTW     $0x0001, DX
	JZ        copyEnd0
	MOVQ      (CX), R14
	ADDQ      BX, R14
	VMOVDQA64 Z8, (R14)

copyEnd0:
	MOVQ      8(AX), R14
	ADDQ      BX, R14
	VMOVDQA64 (R14), Z9
	TESTW     $0x0002, DX
	JZ        copyEnd1
	MOVQ      8(CX), R14
	ADDQ      BX, R14
	VMOVDQA64 Z9, (R14)

copyEnd1:
	MOVQ      16(AX), R14
	ADDQ      BX, R14
	VMOVDQA64 (R14), Z10
	TESTW     $0x0004, DX
	JZ        copyEnd2
	MOVQ      16(CX), R14
	ADDQ      BX, R14
	VMOVDQA64 Z10, (R14)

copyEnd2:
	MOVQ      24(AX), R14
	ADDQ      BX, R14
	VMOVDQA64 (R14), Z11
	TESTW     $0x0008, DX
	JZ        copyEnd3
	MOVQ      24(CX), R14
	ADDQ      BX, R14
	VMOVDQA64 Z11, (R14)

copyEnd3:
	MOVQ      32(AX), R14
	ADDQ      BX, R14
	VMOVDQA64 (R14), Z12
	TESTW     $0x0010, DX
	JZ        copyEnd4
	MOVQ      32(CX), R14
	ADDQ      BX, R14
	VMOVDQA64 Z12, (R14)

copyEnd4:
	MOVQ      40(AX), R14
	ADDQ      BX, R14
	VMOVDQA64 (R14), Z13
	TESTW     $0x0020, DX
	JZ        copyEnd5
	MOVQ      40(CX), R14
	ADDQ      BX, R14
	VMOVDQA64 Z13, (R14)

copyEnd5:
	MOVQ      48(AX), R14
	ADDQ      BX, R14
	VMOVDQA64 (R14), Z14
	TESTW     $0x0040, DX
	JZ        copyEnd6
	MOVQ      48(CX), R14
	ADDQ      BX, R14
	VMOVDQA64 Z14, (R14)

copyEnd6:
	MOVQ      56(AX), R14
	ADDQ      BX, R14
	VMOVDQA64 (R14), Z15
	TESTW     $0x0080, DX
	JZ        copyEnd7
	MOVQ      56(CX), R14
	ADDQ      BX, R14
	VMOVDQA64 Z15, (R14)

copyEnd7:
	MOVQ      64(AX), R14
	ADDQ      BX, R14
	VMOVDQA64 (R14), Z16
	TESTW     $0x0100, DX
	JZ        copyEnd8
	MOVQ      64(CX), R14
	ADDQ      BX, R14
	VMOVDQA64 Z16, (R14)

copyEnd8:
	MOVQ      72(AX), R14
	ADDQ      BX, R14
	VMOVDQA64 (R14), Z17
	TESTW     $0x0200, DX
	JZ        copyEnd9
	MOVQ      72(CX), R14
	ADDQ      BX, R14
	VMOVDQA64 Z17, (R14)

copyEnd9:
	MOVQ      80(AX), R14
	ADDQ      BX, R14
	VMOVDQA64 (R14), Z18
	TESTW     $0x0400, DX
	JZ        copyEnd10
	MOVQ      80(CX), R14
	ADDQ      BX, R14
	VMOVDQA64 Z18, (R14)

copyEnd10:
	MOVQ      88(AX), R14
	ADDQ      BX, R14
	VMOVDQA64 (R14), Z19
	TESTW     $0x0800, DX
	JZ        copyEnd11
	MOVQ      88(CX), R14
	ADDQ      BX, R14
	VMOVDQA64 Z19, (R14)

copyEnd11:
	MOVQ      96(AX), R14
	ADDQ      BX, R14
	VMOVDQA64 (R14), Z20
	TESTW     $0x1000, DX
	JZ        copyEnd12
	MOVQ      96(CX), R14
	ADDQ      BX, R14
	VMOVDQA64 Z20, (R14)

copyEnd12:
	MOVQ      104(AX), R14
	ADDQ      BX, R14
	VMOVDQA64 (R14), Z21
	TESTW     $0x2000, DX
	JZ        copyEnd13
	MOVQ      104(CX), R14
	ADDQ      BX, R14
	VMOVDQA64 Z21, (R14)

copyEnd13:
	MOVQ      112(AX), R14
	ADDQ      BX, R14
	VMOVDQA64 (R14), Z22
	TESTW     $0x4000, DX
	JZ        copyEnd14
	MOVQ      112(CX), R14
	ADDQ      BX, R14
	VMOVDQA64 Z22, (R14)

copyEnd14:
	MOVQ      120(AX), R14
	ADDQ      BX, R14
	VMOVDQA64 (R14), Z23
	TESTW     $0x8000, DX
	JZ        copyEnd15
	MOVQ      120(CX), R14
	ADDQ      BX, R14
	VMOVDQA64 Z23, (R14)

copyEnd15:
	ADDQ         $0x40, BX
	VSHUFPS      $0x44, Z9, Z8, Z24
	VSHUFPS      $0xee, Z9, Z8, Z8
	VSHUFPS      $0x44, Z11, Z10, Z9
	VSHUFPS      $0xee, Z11, Z10, Z10
	VSHUFPS      $0x44, Z13, Z12, Z11
	VSHUFPS      $0xee, Z13, Z12, Z12
	VSHUFPS      $0x44, Z15, Z14, Z13
	VSHUFPS      $0xee, Z15, Z14, Z14
	VSHUFPS      $0x44, Z17, Z16, Z15
	VSHUFPS      $0xee, Z17, Z16, Z16
	VSHUFPS      $0x44, Z19, Z18, Z17
	VSHUFPS      $0xee, Z19, Z18, Z18
	VSHUFPS      $0x44, Z21, Z20, Z19
	VSHUFPS      $0xee, Z21, Z20, Z20
	VSHUFPS      $0x44, Z23, Z22, Z21
	VSHUFPS      $0xee, Z23, Z22, Z22
	VSHUFPS      $0x88, Z9, Z24, Z23
	VSHUFPS      $0xdd, Z9, Z24, Z24
	VSHUFPS      $0x88, Z10, Z8, Z9
	VSHUFPS      $0xdd, Z10, Z8, Z8
	VSHUFPS      $0x88, Z13, Z11, Z10
	VSHUFPS      $0xdd, Z13, Z11, Z11
	VSHUFPS      $0x88, Z14, Z12, Z13
	VSHUFPS      $0xdd, Z14, Z12, Z12
	VSHUFPS      $0x88, Z17, Z15, Z14
	VSHUFPS      $0xdd, Z17, Z15, Z15
	VSHUFPS      $0x88, Z18, Z16, Z17
	VSHUFPS      $0xdd, Z18, Z16, Z16
	VSHUFPS      $0x88, Z21, Z19, Z18
	VSHUFPS      $0xdd, Z21, Z19, Z19
	VSHUFPS      $0x88, Z22, Z20, Z21
	VSHUFPS      $0xdd, Z22, Z20, Z20
	VSHUFI32X4   $0x44, Z10, Z23, Z22
	VSHUFI32X4   $0xee, Z10, Z23, Z23
	VSHUFI32X4   $0x44, Z11, Z24, Z10
	VSHUFI32X4   $0xee, Z11, Z24, Z24
	VSHUFI32X4   $0x44, Z13, Z9, Z11
	VSHUFI32X4   $0xee, Z13, Z9, Z9
	VSHUFI32X4   $0x44, Z12, Z8, Z13
	VSHUFI32X4   $0xee, Z12, Z8, Z8
	VSHUFI32X4   $0x44, Z18, Z14, Z12
	VSHUFI32X4   $0xee, Z18, Z14, Z14
	VSHUFI32X4   $0x44, Z19, Z15, Z18
	VSHUFI32X4   $0xee, Z19, Z15, Z15
	VSHUFI32X4   $0x44, Z21, Z17, Z19
	VSHUFI32X4   $0xee, Z21, Z17, Z17
	VSHUFI32X4   $0x44, Z20, Z16, Z21
	VSHUFI32X4   $0xee, Z20, Z16, Z16
	VSHUFI32X4   $0x88, Z12, Z22, Z20
	VSHUFI32X4   $0xdd, Z12, Z22, Z22
	VSHUFI32X4   $0x88, Z18, Z10, Z12
	VSHUFI32X4   $0xdd, Z18, Z10, Z10
	VSHUFI32X4   $0x88, Z19, Z11, Z18
	VSHUFI32X4   $0xdd, Z19, Z11, Z11
	VSHUFI32X4   $0x88, Z21, Z13, Z19
	VSHUFI32X4   $0xdd, Z21, Z13, Z13
	VSHUFI32X4   $0x88, Z14, Z23, Z21
	VSHUFI32X4   $0xdd, Z14, Z23, Z23
	VSHUFI32X4   $0x88, Z15, Z24, Z14
	VSHUFI32X4   $0xdd, Z15, Z24, Z24
	VSHUFI32X4   $0x88, Z17, Z9, Z15
	VSHUFI32X4   $0xdd, Z17, Z9, Z9
	VSHUFI32X4   $0x88, Z16, Z8, Z17
	VSHUFI32X4   $0xdd, Z16, Z8, Z8
	VPBROADCASTD SI, Z16
	VPBROADCASTD DI, Z25
	VPBROADCASTD R8, Z26
	VPBROADCASTD R9, Z27
	VPBROADCASTD R10, Z28
	VPBROADCASTD R11, Z29
	VPBROADCASTD R12, Z30
	VPBROADCASTD R13, Z31
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z20, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z12, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z18, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z19, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z22, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z10, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z11, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z13, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z21, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z14, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z15, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z17, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z23, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z24, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z9, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z8, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z18, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z11, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z19, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z15, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z13, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z20, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z22, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z24, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z12, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z17, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z23, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z10, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z14, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z9, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z8, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z21, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z19, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z22, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z15, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z23, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z24, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z18, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z13, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z9, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z11, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z10, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z14, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z20, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z17, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z8, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z21, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z12, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z15, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z13, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z23, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z14, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z9, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z19, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z24, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z8, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z22, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z20, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z17, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z18, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z10, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z21, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z12, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z11, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z23, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z24, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z14, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z17, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z8, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z15, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z9, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z21, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z13, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z18, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z10, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z19, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z20, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z12, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z11, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z22, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z14, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z9, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z17, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z10, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z21, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z23, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z8, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z12, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z24, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z19, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z20, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z15, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z18, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z11, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z22, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z13, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z17, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z0, Z4, Z0
	VPADDD       Z0, Z8, Z0
	VPXORD       Z28, Z0, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z16, Z28, Z16
	VPXORD       Z4, Z16, Z4
	VPRORD       $0x07, Z4, Z4
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z10, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z1, Z5, Z1
	VPADDD       Z1, Z20, Z1
	VPXORD       Z29, Z1, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z25, Z29, Z25
	VPXORD       Z5, Z25, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z12, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z2, Z6, Z2
	VPADDD       Z2, Z14, Z2
	VPXORD       Z30, Z2, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z26, Z30, Z26
	VPXORD       Z6, Z26, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z21, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z3, Z7, Z3
	VPADDD       Z3, Z11, Z3
	VPXORD       Z31, Z3, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z27, Z31, Z27
	VPXORD       Z7, Z27, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z9, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x10, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x0c, Z5, Z5
	VPADDD       Z0, Z5, Z0
	VPADDD       Z0, Z15, Z0
	VPXORD       Z31, Z0, Z31
	VPRORD       $0x08, Z31, Z31
	VPADDD       Z26, Z31, Z26
	VPXORD       Z5, Z26, Z5
	VPRORD       $0x07, Z5, Z5
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z18, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x10, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x0c, Z6, Z6
	VPADDD       Z1, Z6, Z1
	VPADDD       Z1, Z23, Z1
	VPXORD       Z28, Z1, Z28
	VPRORD       $0x08, Z28, Z28
	VPADDD       Z27, Z28, Z27
	VPXORD       Z6, Z27, Z6
	VPRORD       $0x07, Z6, Z6
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z19, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x10, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x0c, Z7, Z7
	VPADDD       Z2, Z7, Z2
	VPADDD       Z2, Z22, Z2
	VPXORD       Z29, Z2, Z29
	VPRORD       $0x08, Z29, Z29
	VPADDD       Z16, Z29, Z16
	VPXORD       Z7, Z16, Z7
	VPRORD       $0x07, Z7, Z7
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z13, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x10, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x0c, Z4, Z4
	VPADDD       Z3, Z4, Z3
	VPADDD       Z3, Z24, Z3
	VPXORD       Z30, Z3, Z30
	VPRORD       $0x08, Z30, Z30
	VPADDD       Z25, Z30, Z25
	VPXORD       Z4, Z25, Z4
	VPRORD       $0x07, Z4, Z4
	VPXORD       Z0, Z16, Z0
	VPXORD       Z1, Z25, Z1
	VPXORD       Z2, Z26, Z2
	VPXORD       Z3, Z27, Z3
	VPXORD       Z4, Z28, Z4
	VPXORD       Z5, Z29, Z5
	VPXORD       Z6, Z30, Z6
	VPXORD       Z7, Z31, Z7
	CMPQ         BX, $0x00000800
	JNE          loopStart
	VSHUFPS      $0x44, Z1, Z0, Z8
	VSHUFPS      $0xee, Z1, Z0, Z0
	VSHUFPS      $0x44, Z3, Z2, Z1
	VSHUFPS      $0xee, Z3, Z2, Z2
	VSHUFPS      $0x44, Z5, Z4, Z3
	VSHUFPS      $0xee, Z5, Z4, Z4
	VSHUFPS      $0x44, Z7, Z6, Z5
	VSHUFPS      $0xee, Z7, Z6, Z6
	VSHUFPS      $0x88, Z1, Z8, Z7
	VSHUFPS      $0xdd, Z1, Z8, Z8
	VSHUFPS      $0x88, Z2, Z0, Z1
	VSHUFPS      $0xdd, Z2, Z0, Z0
	VSHUFPS      $0x88, Z5, Z3, Z2
	VSHUFPS      $0xdd, Z5, Z3, Z3
	VSHUFPS      $0x88, Z6, Z4, Z5
	VSHUFPS      $0xdd, Z6, Z4, Z4
	VSHUFI32X4   $0x44, Z2, Z7, Z6
	VSHUFI32X4   $0xee, Z2, Z7, Z7
	VSHUFI32X4   $0x44, Z3, Z8, Z2
	VSHUFI32X4   $0xee, Z3, Z8, Z8
	VSHUFI32X4   $0x44, Z5, Z1, Z3
	VSHUFI32X4   $0xee, Z5, Z1, Z1
	VSHUFI32X4   $0x44, Z4, Z0, Z5
	VSHUFI32X4   $0xee, Z4, Z0, Z0
	VSHUFI32X4   $0x88, Z2, Z6, Z4
	VSHUFI32X4   $0xdd, Z2, Z6, Z6
	VSHUFI32X4   $0x88, Z5, Z3, Z2
	VSHUFI32X4   $0xdd, Z5, Z3, Z3
	VSHUFI32X4   $0x88, Z8, Z7, Z5
	VSHUFI32X4   $0xdd, Z8, Z7, Z7
	VSHUFI32X4   $0x88, Z0, Z1, Z8
	VSHUFI32X4   $0xdd, Z0, Z1, Z1
	MOVQ         hash1+16(FP), SI
	MOVQ         hash2+24(FP), DI
	MOVQ         (SI), R8
	VMOVDQA64    Y4, (R8)
	MOVQ         (DI), R8
	VMOVDQU64    Y4, (R8)
	VSHUFI32X4   $0xee, Z4, Z4, Z4
	MOVQ         8(SI), R8
	VMOVDQA64    Y4, (R8)
	MOVQ         8(DI), R8
	VMOVDQU64    Y4, (R8)
	MOVQ         16(SI), R8
	VMOVDQA64    Y2, (R8)
	MOVQ         16(DI), R8
	VMOVDQU64    Y2, (R8)
	VSHUFI32X4   $0xee, Z2, Z2, Z2
	MOVQ         24(SI), R8
	VMOVDQA64    Y2, (R8)
	MOVQ         24(DI), R8
	VMOVDQU64    Y2, (R8)
	MOVQ         32(SI), R8
	VMOVDQA64    Y6, (R8)
	MOVQ         32(DI), R8
	VMOVDQU64    Y6, (R8)
	VSHUFI32X4   $0xee, Z6, Z6, Z6
	MOVQ         40(SI), R8
	VMOVDQA64    Y6, (R8)
	MOVQ         40(DI), R8
	VMOVDQU64    Y6, (R8)
	MOVQ         48(SI), R8
	VMOVDQA64    Y3, (R8)
	MOVQ         48(DI), R8
	VMOVDQU64    Y3, (R8)
	VSHUFI32X4   $0xee, Z3, Z3, Z3
	MOVQ         56(SI), R8
	VMOVDQA64    Y3, (R8)
	MOVQ         56(DI), R8
	VMOVDQU64    Y3, (R8)
	MOVQ         64(SI), R8
	VMOVDQA64    Y5, (R8)
	MOVQ         64(DI), R8
	VMOVDQU64    Y5, (R8)
	VSHUFI32X4   $0xee, Z5, Z5, Z5
	MOVQ         72(SI), R8
	VMOVDQA64    Y5, (R8)
	MOVQ         72(DI), R8
	VMOVDQU64    Y5, (R8)
	MOVQ         80(SI), R8
	VMOVDQA64    Y8, (R8)
	MOVQ         80(DI), R8
	VMOVDQU64    Y8, (R8)
	VSHUFI32X4   $0xee, Z8, Z8, Z8
	MOVQ         88(SI), R8
	VMOVDQA64    Y8, (R8)
	MOVQ         88(DI), R8
	VMOVDQU64    Y8, (R8)
	MOVQ         96(SI), R8
	VMOVDQA64    Y7, (R8)
	MOVQ         96(DI), R8
	VMOVDQU64    Y7, (R8)
	VSHUFI32X4   $0xee, Z7, Z7, Z7
	MOVQ         104(SI), R8
	VMOVDQA64    Y7, (R8)
	MOVQ         104(DI), R8
	VMOVDQU64    Y7, (R8)
	MOVQ         112(SI), R8
	VMOVDQA64    Y1, (R8)
	MOVQ         112(DI), R8
	VMOVDQU64    Y1, (R8)
	VSHUFI32X4   $0xee, Z1, Z1, Z1
	MOVQ         120(SI), R8
	VMOVDQA64    Y1, (R8)
	MOVQ         120(DI), R8
	VMOVDQU64    Y1, (R8)
	TESTW        $0x0001, DX
	JZ           copyEnd20
	MOVQ         BX, SI
	MOVQ         (AX), DI
	MOVQ         (CX), R8
	ADDQ         SI, DI
	ADDQ         SI, R8

loopCopyStart0:
	VMOVDQA64 (DI), Z0
	VMOVDQA64 Z0, (R8)
	ADDQ      $0x40, DI
	ADDQ      $0x40, R8
	ADDQ      $0x40, SI
	CMPQ      SI, $0x00001000
	JNE       loopCopyStart0

copyEnd20:
	TESTW $0x0002, DX
	JZ    copyEnd21
	MOVQ  BX, SI
	MOVQ  8(AX), DI
	MOVQ  8(CX), R8
	ADDQ  SI, DI
	ADDQ  SI, R8

loopCopyStart1:
	VMOVDQA64 (DI), Z0
	VMOVDQA64 Z0, (R8)
	ADDQ      $0x40, DI
	ADDQ      $0x40, R8
	ADDQ      $0x40, SI
	CMPQ      SI, $0x00001000
	JNE       loopCopyStart1

copyEnd21:
	TESTW $0x0004, DX
	JZ    copyEnd22
	MOVQ  BX, SI
	MOVQ  16(AX), DI
	MOVQ  16(CX), R8
	ADDQ  SI, DI
	ADDQ  SI, R8

loopCopyStart2:
	VMOVDQA64 (DI), Z0
	VMOVDQA64 Z0, (R8)
	ADDQ      $0x40, DI
	ADDQ      $0x40, R8
	ADDQ      $0x40, SI
	CMPQ      SI, $0x00001000
	JNE       loopCopyStart2

copyEnd22:
	TESTW $0x0008, DX
	JZ    copyEnd23
	MOVQ  BX, SI
	MOVQ  24(AX), DI
	MOVQ  24(CX), R8
	ADDQ  SI, DI
	ADDQ  SI, R8

loopCopyStart3:
	VMOVDQA64 (DI), Z0
	VMOVDQA64 Z0, (R8)
	ADDQ      $0x40, DI
	ADDQ      $0x40, R8
	ADDQ      $0x40, SI
	CMPQ      SI, $0x00001000
	JNE       loopCopyStart3

copyEnd23:
	TESTW $0x0010, DX
	JZ    copyEnd24
	MOVQ  BX, SI
	MOVQ  32(AX), DI
	MOVQ  32(CX), R8
	ADDQ  SI, DI
	ADDQ  SI, R8

loopCopyStart4:
	VMOVDQA64 (DI), Z0
	VMOVDQA64 Z0, (R8)
	ADDQ      $0x40, DI
	ADDQ      $0x40, R8
	ADDQ      $0x40, SI
	CMPQ      SI, $0x00001000
	JNE       loopCopyStart4

copyEnd24:
	TESTW $0x0020, DX
	JZ    copyEnd25
	MOVQ  BX, SI
	MOVQ  40(AX), DI
	MOVQ  40(CX), R8
	ADDQ  SI, DI
	ADDQ  SI, R8

loopCopyStart5:
	VMOVDQA64 (DI), Z0
	VMOVDQA64 Z0, (R8)
	ADDQ      $0x40, DI
	ADDQ      $0x40, R8
	ADDQ      $0x40, SI
	CMPQ      SI, $0x00001000
	JNE       loopCopyStart5

copyEnd25:
	TESTW $0x0040, DX
	JZ    copyEnd26
	MOVQ  BX, SI
	MOVQ  48(AX), DI
	MOVQ  48(CX), R8
	ADDQ  SI, DI
	ADDQ  SI, R8

loopCopyStart6:
	VMOVDQA64 (DI), Z0
	VMOVDQA64 Z0, (R8)
	ADDQ      $0x40, DI
	ADDQ      $0x40, R8
	ADDQ      $0x40, SI
	CMPQ      SI, $0x00001000
	JNE       loopCopyStart6

copyEnd26:
	TESTW $0x0080, DX
	JZ    copyEnd27
	MOVQ  BX, SI
	MOVQ  56(AX), DI
	MOVQ  56(CX), R8
	ADDQ  SI, DI
	ADDQ  SI, R8

loopCopyStart7:
	VMOVDQA64 (DI), Z0
	VMOVDQA64 Z0, (R8)
	ADDQ      $0x40, DI
	ADDQ      $0x40, R8
	ADDQ      $0x40, SI
	CMPQ      SI, $0x00001000
	JNE       loopCopyStart7

copyEnd27:
	TESTW $0x0100, DX
	JZ    copyEnd28
	MOVQ  BX, SI
	MOVQ  64(AX), DI
	MOVQ  64(CX), R8
	ADDQ  SI, DI
	ADDQ  SI, R8

loopCopyStart8:
	VMOVDQA64 (DI), Z0
	VMOVDQA64 Z0, (R8)
	ADDQ      $0x40, DI
	ADDQ      $0x40, R8
	ADDQ      $0x40, SI
	CMPQ      SI, $0x00001000
	JNE       loopCopyStart8

copyEnd28:
	TESTW $0x0200, DX
	JZ    copyEnd29
	MOVQ  BX, SI
	MOVQ  72(AX), DI
	MOVQ  72(CX), R8
	ADDQ  SI, DI
	ADDQ  SI, R8

loopCopyStart9:
	VMOVDQA64 (DI), Z0
	VMOVDQA64 Z0, (R8)
	ADDQ      $0x40, DI
	ADDQ      $0x40, R8
	ADDQ      $0x40, SI
	CMPQ      SI, $0x00001000
	JNE       loopCopyStart9

copyEnd29:
	TESTW $0x0400, DX
	JZ    copyEnd210
	MOVQ  BX, SI
	MOVQ  80(AX), DI
	MOVQ  80(CX), R8
	ADDQ  SI, DI
	ADDQ  SI, R8

loopCopyStart10:
	VMOVDQA64 (DI), Z0
	VMOVDQA64 Z0, (R8)
	ADDQ      $0x40, DI
	ADDQ      $0x40, R8
	ADDQ      $0x40, SI
	CMPQ      SI, $0x00001000
	JNE       loopCopyStart10

copyEnd210:
	TESTW $0x0800, DX
	JZ    copyEnd211
	MOVQ  BX, SI
	MOVQ  88(AX), DI
	MOVQ  88(CX), R8
	ADDQ  SI, DI
	ADDQ  SI, R8

loopCopyStart11:
	VMOVDQA64 (DI), Z0
	VMOVDQA64 Z0, (R8)
	ADDQ      $0x40, DI
	ADDQ      $0x40, R8
	ADDQ      $0x40, SI
	CMPQ      SI, $0x00001000
	JNE       loopCopyStart11

copyEnd211:
	TESTW $0x1000, DX
	JZ    copyEnd212
	MOVQ  BX, SI
	MOVQ  96(AX), DI
	MOVQ  96(CX), R8
	ADDQ  SI, DI
	ADDQ  SI, R8

loopCopyStart12:
	VMOVDQA64 (DI), Z0
	VMOVDQA64 Z0, (R8)
	ADDQ      $0x40, DI
	ADDQ      $0x40, R8
	ADDQ      $0x40, SI
	CMPQ      SI, $0x00001000
	JNE       loopCopyStart12

copyEnd212:
	TESTW $0x2000, DX
	JZ    copyEnd213
	MOVQ  BX, SI
	MOVQ  104(AX), DI
	MOVQ  104(CX), R8
	ADDQ  SI, DI
	ADDQ  SI, R8

loopCopyStart13:
	VMOVDQA64 (DI), Z0
	VMOVDQA64 Z0, (R8)
	ADDQ      $0x40, DI
	ADDQ      $0x40, R8
	ADDQ      $0x40, SI
	CMPQ      SI, $0x00001000
	JNE       loopCopyStart13

copyEnd213:
	TESTW $0x4000, DX
	JZ    copyEnd214
	MOVQ  BX, SI
	MOVQ  112(AX), DI
	MOVQ  112(CX), R8
	ADDQ  SI, DI
	ADDQ  SI, R8

loopCopyStart14:
	VMOVDQA64 (DI), Z0
	VMOVDQA64 Z0, (R8)
	ADDQ      $0x40, DI
	ADDQ      $0x40, R8
	ADDQ      $0x40, SI
	CMPQ      SI, $0x00001000
	JNE       loopCopyStart14

copyEnd214:
	TESTW $0x8000, DX
	JZ    copyEnd215
	MOVQ  BX, DX
	MOVQ  120(AX), AX
	MOVQ  120(CX), CX
	ADDQ  DX, AX
	ADDQ  DX, CX

loopCopyStart15:
	VMOVDQA64 (AX), Z0
	VMOVDQA64 Z0, (CX)
	ADDQ      $0x40, AX
	ADDQ      $0x40, CX
	ADDQ      $0x40, DX
	CMPQ      DX, $0x00001000
	JNE       loopCopyStart15

copyEnd215:
	RET
