// Code generated by command: go run avo.go -out ../asm.s -stubs ../asm_stub.go -pkg hash. DO NOT EDIT.

package hash

// Blake34096 implements blake3 for 16 4KB messages.
func Blake34096(blocks **byte, hashes **byte, mask uint16)

// Blake32048 implements blake3 for 16 2KB messages.
func Blake32048(blocks **byte, hashes **byte, mask uint16)
