// Code generated by command: go run avo.go -out ../asm.s -stubs ../asm_stub.go -pkg hash. DO NOT EDIT.

package hash

// Blake3AndCopy4096 implements blake3 for 16 4KB messages.
func Blake3AndCopy4096(blocks **byte, copy **byte, hash1 **byte, hash2 **byte)

// Blake3AndCopy2048 implements blake3 for 16 2KB messages.
func Blake3AndCopy2048(blocks **byte, copy **byte, hash1 **byte, hash2 **byte)
