// Code generated by command: go run avo.go -out ../asm.s -stubs ../asm_stub.go -pkg wal. DO NOT EDIT.

#include "textflag.h"

// func Copy(x *byte, y *byte, z *byte)
// Requires: AVX512F
TEXT ·Copy(SB), NOSPLIT, $0-24
	MOVQ      z+16(FP), AX
	VMOVDQU64 (AX), Z0
	MOVQ      x+0(FP), AX
	VMOVDQU64 Z0, (AX)
	MOVQ      y+8(FP), AX
	VMOVDQU64 Z0, (AX)
	RET
